{970}{1042}- Exiting the time knot now, sir.|- We're alive !
{1043}{1092}We made it, Commander.|We made it.
{1094}{1172}By Grabthar's hammer,|we live to tell the tale.
{1174}{1226}Systems registering functional.
{1228}{1277}All systems are|working, Commander.
{1279}{1364}I don't like it.|It was too easy.
{1366}{1471}- Wait ! Oh, no.|They're everywhere !
{1473}{1537}- There are time knots|opening everywhere !|- A trap !
{1539}{1598}We're surrounded,|Commander.
{1631}{1709}- Aah !|- Ooh !
{1711}{1764}It's a core meltdown, sir.|It can't be stopped.
{1766}{1833}Surrender may be|our only option.
{1835}{1889}No ! Never give up !
{1890}{1937}Never surrender !
{1938}{1994}Your orders, sir ?
{2038}{2096}Sir ?|Group orders ?
{2153}{2225}Activate the Omega 13.
{2263}{2339}- Well ?
{2341}{2438}Huh ?|Well, there you are.
{2440}{2504}- Yeah ! Huh ?
{2533}{2645}Yeah ! Yeah, that's|what I'm talking about.
{2647}{2757}You are the first people|to see the lost Galaxy Quest--
{2759}{2829}episode 92|two-parter--
{2830}{2892}since it was originally aired|in 1982 !
{2894}{2983}- Huh ? Yeah ! All right.
{2985}{3056}And now, the moment you've|all been waiting for--
{3058}{3182}the intrepid crew|of the N.S.E.A. Protector !
{3184}{3231}- Yeah ! Yeah !
{3232}{3350}[ Man ]|Red scarf, black shoes. Wait.
{3352}{3462}White scarf, black buttons,|white shoes.
{3508}{3576}Man, where in the hell is he ?|An hour and a half late ?
{3578}{3653}- An hour and a half.|- I mean, this is unreal.
{3655}{3711}They're gonna start|eating each other out there.
{3713}{3793}Oh, did you hear ? He booked|another appearance without us.
{3794}{3842}You're kidding .
{3879}{3952}Oh. Uh--|Um--
{4038}{4093}- How did I come to this ?|- Not again.
{4095}{4164}- I played Richard the Third.|- Five curtain calls.
{4166}{4243}There were five curtain calls.|I was an actor once, damn it !|Now look at me. Look at me !
{4244}{4299}I cannot go out there,|and I won't say...
{4300}{4391}that stupid line|one more time !
{4393}{4467}- I can't, I won't.|- Well, Alex, at least you had a part.
{4469}{4526}Okay ? You had|a character people loved.
{4528}{4598}I mean, my TV Guide interview|was six paragraphs...
{4600}{4670}about my boobs and how they|fit into my suit.
{4672}{4749}No one even bothered to ask me|what I do on the show.
{4785}{4874}You had the-- Wait.|Wait, I'll think of it.
{4876}{4956}- I repeated the computer, Fred.|- Whew !
{4958}{5038}Your commander is on deck !|Ha, ha !
{5040}{5108}Wow, that smog|is thick today, huh ?
{5110}{5179}- Am I too late for|Alexander's panic attack ?
{5180}{5251}Apparently not. You know,|you should get that looked at.
{5252}{5322}Yeah.
{5323}{5386}Let's take a look at a few more clips.
{5388}{5478}Okay.|What did I do ? Hmm ?
{5480}{5533}We want the crew !|- What ?
{5535}{5624}- We want the crew !|- For those four seasons,|we developed the same affection...
{5626}{5706}for the crew as the crew|had for each other.
{5708}{5779}These weren't just adventurers|exploring space.
{5781}{5828}- Friends.|- These were friends.
{5829}{5897}- Unbelievable.|- You are so full of it, man !
{5898}{5958}It's not a big deal ! These guys|put a little set in their basement.
{5959}{6045}I'm there about an hour.|It's nothing, Gwen.
{6046}{6087}They wanted|the Commander.
{6089}{6162}- There he goes.|- Alexander, wait a minute.|Grab him ! Grab him !
{6163}{6237}- We want the crew ! We want the crew !|- Okay !
{6238}{6307}Yeah !|Here we go !
{6308}{6371}Come on, old friend.|Old friend.
{6373}{6445}You stole all my best lines.|You cut me out of episode two entirely.
{6447}{6534}- Excuse me.|- Tawny Madison--|my personal favorite--
{6536}{6593}- Gwen DeMarco !
{6595}{6638}Yeah !
{6695}{6762}Yeah, that's what I'm talking about !|Let's hear a warm welcome...
{6764}{6876}for crack gunner Laredo--|Tommy Webber !
{6913}{6961}- You will go out there !|- I won't,
{6963}{7010}and nothing you say|will make me.
{7011}{7105}- The show must go on.|- Freddie Kwan !
{7151}{7204}- Damn you.
{7206}{7311}Damn you. I won't say|that stupid line one more time.
{7312}{7403}Tev'Meck--|Alexander Dane !
{7404}{7451}Yeah !|All right !
{7520}{7627}By Grabthar's hammer,|you shall be avenged !
{7628}{7710}Yeah !|All right !
{7712}{7788}That guy can act.|And finally,
{7789}{7855}my-- my fellow|Questerians,
{7857}{7970}the brave Commander|of the N.S.E.A. Protector,
{7971}{8023}Peter, Peter, Peter,|Peter, Peter,
{8025}{8118}Quincy, Quincy, Quincy, Quincy,|Taggart, Taggart, Taggart, Taggart--
{8119}{8221}- Jason Nesmith ! Yes !
{8349}{8410}We love you, Commander !
{8450}{8534}- Never give up, never--|Never surrender !
{8536}{8626}Damn the resonance cannons,|full speed ahead ! Huh ?
{8694}{8772}The Commander and his crew|will be signing autographs...
{8774}{8859}on Imperial decks "C" and "B"|near the Coke machines.
{8861}{8954}Whoo ! Quest forever, man !
{8965}{9016}Excuse me, pardon me.|Crew member coming through.
{9018}{9084}- Fans, right ? Hey, Gwen.|- Oh, hey, man.
{9086}{9138}I want to thank you for that|nice intro you gave us today.
{9140}{9201}- Um--|- Guy.
{9203}{9257}You probably don't remember me,|do you ? It's the sunglasses, right ?
{9259}{9323}I was on the show in '82,|episode 81.
{9324}{9424}Got killed by a lava monster|before the first commercial. Aaah !
{9426}{9538}Listen, uh-- Maybe I could sit in|and, uh, sign a couple autographs ?
{9540}{9639}By Grabthar's hammer, by the sons|of Warvan, I shall avenge you !
{9769}{9877}- By Grabthar's--|- Next.
{9879}{9969}Had I moved an inch to the left,|the beast would have killed me.
{9970}{10045}- On the other hand,|my crew was in danger.|- How did you know what to do ?
{10047}{10150}Come on ! Without my crew,|I'm not a commander, huh ?
{10151}{10226}I think we all remember what happened|to that beast on Enok Seven, right ?
{10285}{10378}You've gotta admit,|they really do love him.
{10379}{10436}Yeah, almost as much|as he loves himself.
{10488}{10553}Excuse me, Commander.|Hey !
{10555}{10676}I was wondering if you|could help settle a dispute|my crew and I seem to be having .
{10678}{10747}Um, if you remember, uh,|in "Quasar Dilemma--"
{10749}{10812}Excuse me|for a minute, fellas.
{10861}{10913}I hadn't even gotten|to the relevant conundrum.
{10914}{10989}In episode 15,|"Mist of Delos Five,"
{10990}{11090}I got the feeling that you and|the Commander kind of had a thing .
{11091}{11151}- Did you ?|- No.
{11152}{11202}The Commander and I|never had a thing .
{11204}{11272}Well that's|her story.
{11365}{11439}Excuse me.
{11441}{11529}Gwen. Gwen.
{11584}{11629}Gwen.
{11655}{11701}- Commander.|- Excuse me.
{11703}{11758}I must speak to you.|It is a matter of supreme importance.
{11760}{11823}We are Thermians|from the Klatu Nebula...
{11825}{11873}and we... need your help.
{11875}{11925}Oh, oh, oh.
{11926}{11973}Is this about|that gig tomorrow ?
{11974}{12057}Just hammer out the details|with my agent, and make sure|there's a limo at my house.
{12059}{12155}Last time I did one of these gigs,|they shoved me in the back of a Toyota.
{12157}{12223}Remember,|mum's the word.
{12224}{12289}- Certainly, but um--|- Mum.
{12291}{12357}- Mum. Mum.|- Mum.|- Mum.
{12359}{12448}Look here.|And... beautiful.
{12516}{12584}Crewman Madison.|The mist of this strange planet...
{12586}{12664}is filling my head|with such thoughts.
{12666}{12740}It was cute when I|didn't know you.
{12812}{12868}You--
{13395}{13501}What a freak show, man.|Oh, this is hilarious.
{13503}{13602}Bunch of losers ! Begging|for autographs at 15 bucks a pop.
{13604}{13664}- These guys haven't had|a real acting job for 20 years.
{13666}{13734}- This is all they've got.|- Did you check out Nesmith ?
{13736}{13808}He actually gets off on those retards|thinking he's a space commander !
{13810}{13858}- Yeah ! Oh, and his friends ?|- I know !
{13860}{13926}They can't stand him ! Did you|hear them ragging on him in there ?
{13928}{14010}Dude, he has no idea he's|a laughing stock, even to his buddies.
{14011}{14073}- He's pathetic !|- Ooh, come on, come on.
{14075}{14121}The Galaxy Quest Dancers|are almost on.
{14123}{14198}Whoo ! Full speed ahead,|Lieutenant.
{14499}{14578}Hey, Commander,|uh, so, as I was saying ,
{14580}{14640}in "The Quasar Dilemma," remember,|you used the auxiliary of deck B--
{14642}{14709}could you get this--|deck B for gamma override.
{14710}{14775}The thing is... is that|online blueprints clearly indicate...
{14777}{14848}that deck B is independent|of the guidance matrix.
{14850}{14925}So, we were wondering |just where the error lies in that.
{14927}{15013}It's just a television show.|That's all, okay ?
{15015}{15062}Right, but--
{15063}{15117}'Cause we were wondering if the quantum|flux-- Now, just listen on this--
{15119}{15175}There is no|quantum flux !
{15177}{15283}There's no auxiliary.|There's no goddamn ship !
{15285}{15347}You got it ?
{15586}{15636}I mean it.|I mean it, Alex.
{15637}{15708}I've never seen him lose it like that.|Not to a fan.
{15710}{15757}I mean, it was|just weird.
{15758}{15865}Gwen, I have|said it for years.
{15867}{15914}He's mentally unstable.
{15916}{15982}I-- I'm worried.
{15984}{16034}It just was not|like him.
{16502}{16575}As long as there|is injustice,
{16577}{16648}whenever a Targathian baby|cries out,
{16650}{16725}- wherever a distress signal|sounds among the stars,
{16727}{16833}-we'll be there-- this fine|ship, this fine crew.|-This fine ship, this fine crew.
{16835}{16913}- Never give up and never surrender.|- Never give up.
{16915}{16980}Never surrender.
{18318}{18414}- Can I help you ?|- Sir, I understand this is|a terrible breach in protocol--
{18416}{18490}- You guys shouldn't come|to my house, man.|- I beg you to hear our plea.
{18492}{18554}We are Thermians|from the Klatu Nebula.
{18556}{18634}Our people are being systematically|hunted and slaughtered...
{18636}{18682}by Roth'h'ar Sarris|of Fatu-Krey.
{18684}{18797}We are to meet in negotiation.|However, our efforts in this|regard have been disastrous.
{18798}{18913}Please, Commander.|You are our last hope.
{18975}{19046}- We have secured our limousine.|- What ?
{19047}{19114}Oh, oh, oh, oh.
{19115}{19213}Um, it's the thing |for the thing that's, um--
{19263}{19328}Maybe I should get some pants on.
{19375}{19421}Come on in.
{19505}{19560}- Commander,
{19561}{19626}I must say that standing here|in your presence...
{19628}{19737}is the greatest honor we could have|ever hoped to achieve in our lifetimes.
{19739}{19799}That's-- I really|appreciate that.
{19801}{19872}Would you guys look for another shoe|that looks like this, please ?
{20107}{20180}Sir, I am Lahnk,|senior requisition officer.
{20182}{20262}Before we travel to the ship, please let|me know if you have any requirements.
{20263}{20366}- Weapons, documents, personnel ?|- Um, a Coca-Cola ?|Do you have one of those ?
{20408}{20481}- Sir, I am Teb.
{20483}{20529}I would like to explain|the history between our people...
{20531}{20617}- and the Sarris Dominion|in greater detail.|- Hey, how ya doing ?
{20619}{20708}In the five million years|following the Great Nebula Burst,
{20709}{20804}- our people were one p--|- What's your name ?
{20805}{20894}- Doesn't she talk ?|- Her translator is broken.
{20963}{21012}- Okeydokey.
{21014}{21129}You know, guys, I had a late night|with a Kreemorian Fangor beast,
{21131}{21233}so I'm gonna just|shut my eyes for a bit.
{21235}{21335}Go on. You know. I'm listening |to everything you say, okay ?
{21336}{21402}In the five million years|following the Great Nebula Burst,
{21404}{21455}our people|were one people.
{21456}{21558}But then came the Zactor Migration,|and then the Melosian Shift,
{21560}{21685}dark period of discontent|once spread through the land.
{21687}{21792}Fighting among Treeb sects|and Largoths-- ah, the foolishness.
{21793}{21865}And it was in this time|of dissension that Sarris--
{22049}{22122}- Commander. Commander.|- Hmm.
{22124}{22233}I'm sorry to wake you, sir,|but your presence is requested|on the command deck.
{22360}{22411}- Sir, Sarris has moved the deadline.
{22412}{22487}We are approaching his ship|at the Ni-delta now.
{22488}{22535}He wants an answer|to his proposal.
{22536}{22599}Yeah, I got most of it in the car.|Sarris is the bad guy, right ?
{22601}{22665}Oh, yes, sir.|He's a very bad man indeed.
{22667}{22746}He has tortured our scientists, put us|to work in the gallium arsenide mines,
{22748}{22813}- Mm-hmm.|- captured our females|for his own demented purposes--
{22815}{22893}Yeah, yeah, I got the picture.|Do you have pages or do you|just want me to wing this ?
{22895}{22949}- I am not sure I understand you.|- Commander.
{22951}{23010}- Welcome to the Protector Two.|- Good to see ya.
{23012}{23084}- Would you like to don your uniform ?|- I'd like to skip that.
{23086}{23157}I got this gig in Van Nuys in about a|quarter of an hour. Is that all right ?
{23159}{23236}- As you wish.|- Sir, it's Sarris.
{23238}{23284}He's here.
{23427}{23519}General, I just received word|the Thermians have appointed|a new commander...
{23521}{23586}to handle|the negotiations.
{23588}{23634}What ?
{23741}{23837}This is great. You know, usually|it's just cardboard walls in a garage.
{23838}{23911}- Sir, we apologize|for operating in low-power mode,|- Oh. Oooh.
{23913}{24033}but we are experiencing |a reflective flex field|this close to the galactic axis.
{24035}{24144}You know what I could use ?|A cup holder and a couple of Advil.
{24146}{24202}We're approaching in five ticks, sir.|Command to slow ?
{24203}{24266}Set it on screen saver two.
{24301}{24370}Because we, you know-- We gotta--
{24371}{24452}Oh, I'm sorry|to break the mood here.
{24454}{24529}Um, slow it down|to mark two, Lieutenant.
{24531}{24577}I see fear.
{24579}{24652}- That is expected.|- Mm-hmm.
{24653}{24752}- Ahh, they bring a new commander.|- It's good.
{24753}{24808}- Here are my demands.|- It's scary.|I mean, you know, he looks...
{24809}{24874}- And if I do not hear what I like,|- real.
{24876}{24932}then there will be blood...
{24934}{25041}and pain|as you cannot imagine !
{25042}{25102}- First, I require...|- Backwash.
{25104}{25159}the Omega 13.
{25161}{25272}Second, I will require|a technician--
{25274}{25399}Okeydokey. Let's fire blue particle|cannons full. Red particle cannons full.
{25401}{25475}Gannet magnets,|fire them left and right.
{25476}{25533}And let 'em run all chutes.|And while you're at it,
{25535}{25582}why don't you toss that|at 'em, killer ?
{25584}{25646}That should take care of|old lobster head, shouldn't it ?
{25877}{25921}Commander,|where are you going ?
{25922}{25971}- Home.|- You-- You mean Earth ?
{25973}{26019}Yeah, Earth. I need|to get back to Earth, kids.
{26022}{26091}But the negotiation.|You-You fired on him.
{26093}{26163}- Yeah, yeah. Long live--|What was your planet called ?|- Thermia.
{26164}{26246}- Long live Thermia. This way ?|- But what if Sarris survives ?
{26247}{26315}- I doubt it. I gave him both barrels.|- He has a very powerful ship.
{26317}{26389}If you got any more problems|with the guy, just give me a call.
{26391}{26437}- Ow !
{26473}{26524}- An interstellar vox.|- A what ? Hey.
{26525}{26599}- How can we thank you, Commander ?
{26600}{26705}You-- You have saved|our people.
{26765}{26876}Yeah. Okay. You know, you kids|have been great. You really have.
{26878}{26997}This thing is real looking.|Yoo-hoo. Hello ?
{27026}{27094}Hey ! Where's my limo ?
{27128}{27175}Huh ?
{28909}{29002}Take it from us.|We've been all over the universe.
{29004}{29128}But we've never seen space-age values|like we've seen here at--
{29130}{29193}Tech Value|Electronic Superstore !
{29376}{29438}By Grabthar's hammer,
{29509}{29567}what a savings.
{29569}{29620}All right !
{29621}{29695}Yeah. Let's hear it|for the N.S.E.A. Protector.
{29796}{29852}- Brandon, are you okay ?|- Commander.
{29853}{29910}My apologies.
{29912}{30001}Evidently, we had a little|miscommunication regarding ...
{30002}{30057}the voyage.
{30058}{30135}That you didn't show up.
{30193}{30273}- He did it again.|Thank you for coming out.
{30275}{30395}Do you know what time it is ? Why do|you even bother to show up at all ?
{30396}{30478}N-N-N-Not now.|Guys, I was there.
{30480}{30557}I was up there.|Remember yesterday at the convention ?
{30559}{30619}Those people dressed like aliens ?|They were aliens.
{30621}{30710}They were Termites or Dalmatians.|I can't really remember|'cause I was hung over.
{30712}{30760}But what they built|was extraordinary.
{30762}{30857}It was a huge spaceship.|I got to fight this guy named Sarris|and I kicked his ass.
{30945}{31047}I know what you're thinking.|But I can prove it. They gave me this.
{31085}{31207}No, no, no, no, no. But can you|talk to people in space on those ?
{31209}{31251}Protector,|this is the commander. Over.
{31253}{31325}- Oh, for God's sake.|- That's it. It's time to go !
{31327}{31389}This isn't mine.
{31391}{31460}- That kid. Where's that kid ?|- Begging your pardon, Commander ?
{31461}{31508}We come with news.|Sarris lives.
{31509}{31575}- He was able upon your departure|to make an escape.|- Listen. Tell them.
{31576}{31646}- However, he has contacted us|and wishes to negotiate a surrender.|- Sarris.
{31648}{31738}We humbly implore you to come|and negotiate the terms.
{31740}{31798}Huh ? They want me back ?|You want me back ?
{31799}{31897}Is this amazing ? They want me back, and|I want you guys to go with me. Please ?
{31899}{31960}Think about it.|Let's go. Yes !
{31962}{32014}You're-- You're going ?
{32016}{32070}Alexander, this is not--|I'm not kidding here.
{32071}{32126}This isn't some kind of prank.|I'm not kidding.
{32127}{32199}No, guys, guys, listen.|Come on. Gwen, Gwen, Gwen.
{32201}{32295}Stop. Come here. You know me, and|I'm a lot of things, but am I crazy ?
{32296}{32359}You know, it's one thing |to treat us this way.
{32360}{32428}It's another thing to do it|to your fans.
{32429}{32527}She's not a fan.|This is-- This is a Termite !
{32528}{32587}You should've just|let me hit him.
{32588}{32686}Boy, I didn't know|you could get that loaded.
{32688}{32767}I think we should've|just taken the gig.
{32769}{32828}I mean, who knows|the next time he'll ask us ?
{32830}{32906}Fred, he was drunk. Do you really think|he was talking about a job ?
{33083}{33135}- But you live with your mother.|- Did Jason come through here ?
{33137}{33206}Yeah, he's in there.|Hey, guys.
{33207}{33293}Ah. We are coming too.
{33295}{33386}- All of you wish to go to the ship ?|- Yes, we wish to go to the ship.
{33387}{33465}You see, we work together,|or not at all.
{33467}{33587}Wonderful. The commander|had me continue transmission|in case you changed your mind.
{33589}{33696}- Protector, requesting |four interstellar--|- Me too.
{33698}{33757}five pods|for immediate departure.
{33842}{33892}Guys.
{33894}{33952}- Guys.|- I look forward to meeting you all...
{33954}{34004}in person when you|arrive at the ship.
{34006}{34077}- End transmission.
{34078}{34158}- Oh, my God.
{34160}{34234}- Anybody got any change ?
{35872}{35924}Our most sincere apologies.
{35926}{36036}- We forgot about|our appearance generators.|- You guys came.
{36038}{36085}Who wants the grand tour ?
{36219}{36278}- Anybody else ?
{36368}{36415}That was a hell of a thing .
{36518}{36581}- What's wrong with them ?|- I don't know. Come on.
{36592}{36656}That's right, guys.|Keep shaking it off. It gets better.
{36658}{36720}- Try some gum. It helps.|- Where are we ?
{36722}{36802}The twenty-third quadrant|of the gamma sector.|There's a map in the forward room.
{36804}{36840}I'll show you.|Come on.
{36842}{36918}- Welcome, my friends.|- This is Mathesar. He's their leader.
{36920}{36995}I am Mathesar.|On behalf of all my people,
{36997}{37074}I wish to thank you from|the deepest place in our hearts.
{37076}{37138}Mathesar,|this is, uh, my crew.
{37209}{37273}Dr. Lazarus.
{37275}{37327}Dr. Lazarus. Dr. Lazarus.
{37329}{37391}Lieutenant Madison.
{37393}{37454}Lieutenant Madison.
{37589}{37659}Young Laredo,|how you've grown.
{37661}{37703}Young Laredo.
{37754}{37805}Tech Sergeant Chen.
{37807}{37874}Tech Sergeant Chen. Tech Sergeant Chen.
{37975}{38070}C-Crew man number--|Guy.
{38071}{38121}Guy.
{38123}{38203}You... know us ?
{38261}{38338}I don't believe there is a man, woman|or child on my planet who does not.
{38339}{38435}Since we first received transmission|of your historical documents,
{38437}{38531}we have studied every facet|of your missions and strategies.
{38533}{38624}- You've been watching the show ?|- Lieutenant, historical documents.
{38625}{38717}- H-Historical documents from out here ?|- Yes.
{38718}{38794}The past hundred years our society|had fallen into disarray.
{38796}{38870}Our goals, our values had become|scattered. But since the transmission,
{38872}{38943}- we have modeled every aspect|of our society...
{38945}{39033}from your example,|and it has saved us.
{39034}{39146}Your courage and teamwork|and friendship through adversity--
{39147}{39222}In fact, all you see around you|has been taken from the lessons...
{39224}{39295}garnered from|the historical documents.
{39297}{39381}- Is this a-- a spaceship ?|- No.
{39383}{39460}This is a star port|for the ship.
{39461}{39519}Would you guys|like to see the ship ?
{40076}{40131}Oh, my God !
{40259}{40312}It's real.
{40521}{40569}The generator room.
{40571}{40642}The beryllium sphere,|of course.
{40644}{40690}And as we continue--
{40692}{40745}The medical quarters|are to the left.
{40747}{40832}We went through some trouble|duplicating your cellular regeneration--
{40834}{40902}- Jason, what have you got us into ?|- What are we doing here ?
{40903}{41000}- Wow, the floors are so clean.|- We're just here to negotiate|this guy Sarris' surrender.
{41002}{41118}- It's no big deal.|- And the organ fabrication chamber|is coming along nicely.
{41119}{41167}It's no big deal ?
{41169}{41278}- Are you crazy ?|We have to get out of here.|- Oh, come on, guys.
{41279}{41334}Jason, we are actors,|not astronauts.
{41336}{41402}You guys wanna go home ?|Say the word, we'll go home.
{41404}{41455}Pay our bills,|feed our fish,
{41457}{41559}fall asleep in front of the TV|and miss out on all of this.
{41561}{41628}Come on. Do you guys|wanna do that ? Anybody ?
{41629}{41696}Gwen, come on.|Look at where we are. We're in space.
{41698}{41804}Alexander, this is the role|of a lifetime. You guys wanna leave ?
{41806}{41901}We have enjoyed preparing |many of your esoteric dishes.
{41903}{41991}Your Monte Cristo sandwich is a current|favorite among the adventurous.
{41993}{42039}The main barracks.
{42371}{42417}At ease.
{42510}{42582}It's like throwing gasoline|on a flame.
{42666}{42713}What ?
{42714}{42791}I'm just jazzed about|being on the show, man.
{42949}{43004}If you would all take your positions.
{43038}{43107}- Our what ?|- Guys.
{43163}{43239}- Oh. Oh.|- Oh.|- Oh, wh-- Hmm.
{43351}{43403}Look, this thingy.
{43437}{43508}I remember--|I remember I had it all worked out.
{43509}{43581}This is forward.|This is back.
{43633}{43739}Commander, some of the crew|has requested to be present|at this historic event.
{43741}{43798}Sure. Bring 'em in.
{44160}{44265}No pressure, huh ?|Glad I ain't the commander.
{44311}{44361}Laredo, take us out.
{44410}{44488}- Excuse me ?
{44489}{44595}They designed those controls|after watching you.
{44597}{44684}- Take her out.|- Right, right.
{44686}{44736}Okay.
{44738}{44800}Right.
{44802}{44882}Right.|Take her out.
{46360}{46406}Okay.
{46408}{46454}Y-you gotta move|to the right.
{46456}{46530}- Hit parallel.|- Would you sit your ass down ?|Sit ! You wanna drive ?
{47737}{47801}Oh. Mmm.
{47803}{47863}How are you enjoying |your steak, Commander ?
{47865}{47957}I'm really enjoying it.|This is like corn-fed lowa beef.
{47958}{48022}Yes. We programmed|the food synthesizer...
{48024}{48094}for each of you based on|the regional menu of your birthplace.
{48096}{48171}I don't care where|you did it. It tastes great !
{48173}{48242}Are you enjoying your|Kep-mok bloodticks, Dr. Lazarus ?
{48244}{48298}Just like Mother|used to make.
{48414}{48476}So, um--|Tell me, Mathesar.
{48478}{48542}This Sarris person|that we're flying to meet,
{48544}{48601}- what does he want, exactly ?
{48602}{48689}He heard about the device--|the Omega 13.
{48691}{48758}Um, what is it ?|What does it do ?
{48760}{48816}We don't know.
{48817}{48883}We were hoping |you could enlighten us.
{49048}{49125}Oh.|The Omega 13 device.
{49127}{49202}We found that on an alien planet.|We don't know what it does either.
{49203}{49278}- Why don't you just turn it on|and see what it does ?
{49333}{49431}It has at its heart a reactor|capable of unthinkable energy.
{49432}{49492}If we were mistaken in our construction,|the device would...
{49493}{49565}act as a molecular explosive,|causing a chain reaction...
{49566}{49624}that would obliterate|all matter in the universe.
{49661}{49745}Has Sarris ever seen any|of the, uh, historical records ?
{49747}{49794}No, thank God, he has not.
{49796}{49916}Oh. So how does he know about|the Omega 13 device ?
{50018}{50122}Our former commander|was not... strong.
{50123}{50183}Former commander ?
{50211}{50292}I am sorry.|You deserve to be shown.
{50294}{50381}The tape was smuggled off|of Sarris' ship.
{50383}{50443}Originally, one of our own|tried to lead.
{50445}{50545}Is that all ?|After three days of this,
{50547}{50620}you still require...|incentive ?
{50691}{50747}I have told you all I know.
{50749}{50813}If you have any mercy within you,|please, let me die.
{50814}{50906}[ Sarris ] When I grow weary|of the noises you make, you shall die.
{51246}{51323}Wait a minute, guys. Come on.|Hold on a minute. You just can't leave.
{51324}{51373}- Give me some time to think.|- He wants to think.
{51375}{51435}No, Jason, that's a wrap.|There's nothing to think about.
{51436}{51515}I'm not even supposed to be here. I'm|just crewman number six. I'm expendable.
{51517}{51611}I'm the guy in the episode who dies|to prove the situation is serious.|I gotta get out.
{51613}{51715}- Commander ?|- We gotta prepare the pods|for my crew's departure.
{51717}{51787}Begging your commander's pardon, sir.|We can't launch pods at the moment.
{51789}{51868}- Sarris will surely detonate|any objects leaving the ship.|- Sarris ?
{51870}{51961}Yes, sir. He's here now. Your presence|is required on the command deck.
{52167}{52214}There's nobody here.
{52215}{52260}While my people are|talented scientists,
{52262}{52327}our attempt to operate|our own technologies...
{52329}{52381}under tactical simulation|have been disastrous.
{52383}{52479}- I have raised Sarris|on zeta frequency.|- Mathesar--
{52480}{52545}We meet again, Commander.
{52547}{52625}Hello, Sarris. How you doing ?
{52627}{52709}Better than my lieutenant.
{52710}{52828}He failed to activate the ship's|neutron armor as quickly as I'd hoped...
{52830}{52879}on our last encounter.
{52881}{52968}Yeah, well, you know,|I'd like to say I'm real sorry|about what happened before.
{52970}{53057}The whole thing was just--|just a misunderstanding .
{53058}{53109}Deliver the device to me,
{53111}{53189}or I will destroy your ship.
{53191}{53268}You know, um,|we'd like do that,
{53269}{53355}but frankly, Sarris, sir, we don't know|what it is or even where it is.
{53356}{53419}You have ten seconds !
{53421}{53486}I don't-- Ten seconds ?|I don't-- There--
{53488}{53587}You know-- Okay. Gosh darn it,|I give up. It's yours. You can have it.
{53589}{53664}You have to give me a minute|to put it in a box for you, okay ?
{53665}{53729}- Gwen.
{53731}{53844}Don't panic. I've dealt with|this guy before. He's as stupid|as he is ugly. Come here.
{53845}{53923}- Jason.|- Not now, Gwen. Sit, sit, sit, sit.
{53925}{53986}We're gonna send everything |we can at him, all right ?
{53987}{54034}- Jason.|- Not now, Gwen !
{54035}{54103}Push these red buttons and send|everything we have towards him, okay ?
{54105}{54183}- Okay.|- All right, Gwen.
{54185}{54299}- Put me back on with him.|- Well, I'm trying to tell you,|you are back with him.
{54301}{54417}Perhaps I'm not as stupid|as I am ugly, Commander.
{54493}{54601}I gave you the...|"kill" gesture.
{54603}{54655}No, you gave me|the "we're dead" signal.
{54656}{54723}I was agreeing with you.|Like I know where the hold button is.
{54725}{54780}Hey, guys.
{54782}{54870}- There's a red, uh, thingy...
{54872}{54921}moving toward the green thingy.
{54923}{55008}- What ?|- Red thingy moving|toward the green thingy.
{55047}{55115}I think-- I think|we're the green thingy.
{55117}{55199}A little present|for you, Commander.
{55200}{55254}We gotta get out of here. Move|this ship. Turn it. Move ! Let's go !
{55667}{55736}- Tommy, let's go !|Get us out of here !|- Jason, what do I do ?
{55738}{55776}Go, go, go !
{55898}{55945}Whoo !
{56061}{56159}They're turning .|They're coming !
{56259}{56340}Thrust ahead, full !
{56342}{56405}Fire at will.
{56463}{56523}- Go faster, Tommy !
{56525}{56625}- I'm going as fast as I can !|- She's still behind us !
{56627}{56697}Well, uh, uh, press turbo. I'm always|saying, "Press the turbo," right ?
{56699}{56766}- Oh, it's here. Right here.|- Press it and hold it down.
{56827}{56874}- Whoo !
{56913}{56971}The enemy is matching velocity.
{56973}{57054}- Enemy is matching velocity.|- We heard it the first time !
{57056}{57131}Gosh, I'm doing it.|I'm repeating the darn computer.
{57133}{57239}Hi, guys. Listen.|They're telling me...
{57241}{57347}the, uh-- the generators|won't take it.
{57348}{57416}The ship is breaking apart|and all that.
{57417}{57470}Just F.Y.I.
{57472}{57567}- We've gotta stop !|- We stop and we die.|Tommy, just hold that down.
{57569}{57664}- You don't hold the turbo down.|It's for quick boosts !|- Oh, like you know.
{57760}{57829}- I remember that sound.
{57831}{57876}That's a bad sound.
{57877}{57977}Wait, wait, wait, wait. We might be able|to lose them in this cloud here.
{57979}{58040}Oh, I don't--|I don't think that's a cloud.
{58042}{58165}- Mathesar, what is this ?|- Tothian minefield left standing |from the Great War of 12185.
{58307}{58393}Oh, God !|Whoo !
{58620}{58737}Could you possibly try|not to hit every single one ?
{58738}{58824}Sorry, man. They're drifting|towards us ! I think they're magnetic !
{58935}{58997}Continue forward, sir ?
{59035}{59081}Patience, Lieutenant.
{59106}{59152}Patience.
{59388}{59458}- We've gotta stop !|- We're almost through this.
{59511}{59583}
{59940}{59990}- You okay ? You all right ?|- Yeah.
{59991}{60075}- Everybody all right ? Where's Tommy ?
{60077}{60161}- Oh, man !|- Tommy ! You all right ?
{60163}{60255}No, my arm is broke--|No, don't touch it. Don't touch it.
{60256}{60332}- I'll take him to medical quarters.|- Thanks, Mathesar.
{60493}{60552}Alex, where are you going ?
{60554}{60632}To see if there's a pub.
{60850}{60935}Forward thruster shaft:|87 percent damage.
{60937}{61032}Aft vector guards:|96 percent damage.
{61034}{61142}Structural breaches|in quadrants 32, 34, 40--
{61144}{61231}- What about the engines ?|- Forward thruster shaft:
{61233}{61320}- 87 percent damage.|- Computer, what about the engines ?
{61322}{61448}- Why don't we have power ?|- The beryllium sphere|has fractured under stress.
{61449}{61548}- It's fractured.|- Can it be repaired ?
{61549}{61671}- Computer, can it be repaired ?|- Damage to beryllium sphere:|irreparable.
{61673}{61785}- New source of beryllium|must be secured.|- We need another one.
{61786}{61849}You broke the ship.|You broke the bloody ship.
{61850}{61896}Eh, ah--
{61898}{61990}Computer, is there a replacement|beryllium sphere on board ?
{61992}{62098}Computer, is there a replacement|beryllium sphere on board ?
{62099}{62211}Negative. No reserve|beryllium sphere exists on board.
{62212}{62296}No, we have no extra|beryllium sphere on board.
{62298}{62358}You know, that is|really getting annoying .
{62360}{62434}Look, I have one job|on this lousy ship.
{62436}{62515}It's stupid,|but I'm gonna do it, okay ?
{62517}{62580}Sure, no problem.
{62721}{62799}A thousand apologies.|We have failed you.
{62801}{62858}How have you failed us ?
{62860}{62984}We have seen you victorious in|much more desperate situations.
{62986}{63078}The fault must lie with us,|with the ship.
{63080}{63166}No, Mathesar, it is not your fault,|and it's not the ship's fault.
{63168}{63215}It's-It's-It's-It's|my fault.
{63216}{63330}-We-We screwed--|-We are not the people you think we are.
{63332}{63383}I don't understand.
{63512}{63640}Didn't you make any TV shows|on your planet ? Any theater, films ?
{63641}{63694}The historical documents|of your culture.
{63696}{63803}Yes, in fact, we have begun to document|our history from your example.
{63805}{63921}No, not historical documents. They're|not all historical documents. I mean,
{63923}{64012}surely you don't think|that Gilligan's Island is a--
{64014}{64075}- Those poor people.
{64107}{64163}Oh, brother.
{64164}{64242}We're screwed.
{64267}{64345}Is there no one on your planet|who behaves in a way...
{64347}{64414}that's contrary|to reality ?
{64416}{64499}You are speaking of--
{64501}{64548}- Deception, lies.|- Deception, lies.
{64549}{64680}We have only recently|become aware of this concept|in our dealings with Sarris.
{64682}{64764}Often, Sarris will say one thing |and do another.
{64766}{64830}Promise us mercy,|but deliver destruction.
{64832}{64915}It is a concept we are beginning |to learn at some great costs.
{64916}{65057}But if you are saying that|any of you could have traits|in common with Sarris--
{65284}{65404}Hey, Commander, listen. We found|some beryllium on a nearby planet.
{65406}{65466}We might be able to get there...
{65468}{65566}if we reconfigure|the solar matrix...
{65568}{65643}in parallel|for endothermic propulsion.
{65645}{65704}What do you think ?
{65782}{65843}- We'll do that !|- All right !
{65845}{65898}That's-That's-That's|right again.
{65900}{65961}That's-- C-C-Come on.|Group hug.
{65962}{66048}- Come on.
{66281}{66369}Dr. Lazarus, I hope|I am not breaching protocol,
{66371}{66468}but I am so very humbled|to stand in your presence.
{66470}{66530}I have studied your missions|extensively.
{66532}{66611}Though I am Thermian, I have lived|my life by your philosophy,
{66613}{66668}by the code|of the Mak'tar.
{66669}{66784}- Oh, good, that's very nice.|- By Grabthar's hammer, Dr. Lazarus.
{66786}{66872}- Don't do that. I'm not kidding .|- I'm sorry, sir, I was just--
{66873}{66921}Just don't.
{66950}{66996}Yes, sir.
{67223}{67288}Never give up,|never surrender.
{67433}{67482}Dr. Lazarus ?
{67484}{67579}Here is your surface mapper. I have|programmed it to the coordinates...
{67581}{67652}of a beryllium sphere|of sufficient density.
{67654}{67778}- Good luck on your mission, sir.|- Thanks.
{67974}{68037}You're doing good,|Tommy.
{68179}{68231}I changed my mind.|I wanna go back.
{68233}{68315}After the fuss you made|about getting left behind ?
{68316}{68365}Yeah, but that's when I thought|I was the crewman...
{68367}{68451}that stays on the ship, and something |is up there, and it kills me.
{68453}{68502}But now I'm thinking I'm the guy|who gets killed by some monster...
{68504}{68550}five minutes after we land|on the planet.
{68552}{68598}You're not gonna die|on the planet, Guy.
{68600}{68663}I'm not ?|Then what's my last name ?
{68664}{68743}It's, uh, uh--|I don't know.
{68745}{68809}Nobody knows !|Do you know why ?
{68811}{68879}Because my character isn't|important enough for a last name,
{68881}{68959}because I'm gonna die|five minutes in.
{68961}{69012}Guy, you have a last name.
{69014}{69089}- Do I ? Do I ?|- Yes !
{69091}{69171}For all you know,|I'm just crewman number six.
{69213}{69295}Mommy ! Mommy ! Mommy !
{69296}{69336}Are we there yet ?
{69338}{69396}- Mommy !|- Tommy !
{69398}{69480}- Look out ! Oh, no !|- Pull out !
{69482}{69531}Oh, yeah !
{69950}{70034}- Don't open that !|It's an alien planet !
{70036}{70115}Is there air ?|You don't know !
{70156}{70295}Seems okay.
{70669}{70716}Here we go.
{70822}{70869}Which way, Alexander ?
{70931}{70978}
{71015}{71062}This way !
{71103}{71150}Wait. No.
{71251}{71313}- That way.|- You were holding it upside down.
{71315}{71368}- Shut up.|- You know, with|all that makeup and stuff,
{71370}{71416}I actually thought|you were smart for a second.
{71417}{71469}You think you could|do better, Laredo ?
{71471}{71542}- All right with that Laredo stuff.|- Oh, we're so screwed.
{71544}{71630}Come on, come on, come on,|if we wanna finish this mission,|we have to use self-control.
{71632}{71698}"Self-control" ?|That's funny, coming from a guy...
{71700}{71792}who slept with every Turekian slave|girl and moon princess on the show.
{71794}{71852}Ever occur to you,|had you been more supportive,|you might've been--
{71906}{72014}Wow. Must be|some sort of mining facility.
{72016}{72119}- Where are the miners ?|- Something bad happened here.
{72120}{72200}- Will you relax ?
{72240}{72366}There they are.|Beryllium spheres. Let's go.
{72980}{73030}Look at that.
{73032}{73157}Would you look at that ?|They look like little children.
{73205}{73263}Could they be the miners ?
{73265}{73335}Sure, they're like|three years old.
{73407}{73459}Miners, not minors.
{73461}{73519}- You lost me.|- I don't like this.
{73521}{73600}- I don't like this at all.|- They are so cute.
{73601}{73700}Sure, they're cute now.|In a second, they're gonna get mean.
{73702}{73789}They're gonna get ugly somehow, then|there's gonna be a million more of them.
{73790}{73887}Look.|There's a little hurt one.
{73958}{73994}Oh.
{74082}{74136}Hi.|Hi there.
{74138}{74212}- Ah !|- Shh !
{74214}{74310}- Did you guys ever watch the show ?
{74312}{74364}See ?
{74366}{74415}They're gonna help|the little hurt one.
{74638}{74715}I'm so sick|of being right.
{74717}{74778}- Let's get out of here before|one of those thing skills Guy.|- Wait a minute.
{74780}{74845}We're not going anywhere without|a beryllium sphere. We need a plan.
{74846}{74910}Fred, I need a diversion|to clear the compound of those things.
{74912}{74973}Then, Alex and Gwen and I|will go get a sphere.
{74975}{75046}Tommy, get up on that ridge,|and if you see them come back,|give me a signal, all right ?
{75048}{75091}Why does this sound|so familiar ?
{75093}{75158}"Assault on Voltareck 3,"|episode 81.
{75159}{75246}- We're doing episode 81 ?|- Whatever. The one with|the hologram, the wall of fire.
{75248}{75323}Well, how the hell is Fred|supposed to project a hologram ?
{75325}{75395}- What did we do in episode 81 ?|- It's just a rough plan.
{75397}{75500}- What difference does it make|if it's episode 81 or not ?|- 'Cause I died in episode 81 !
{75502}{75583}- Shh ! Episode 51, right ?|- This is ludicrous.
{75585}{75631}Why are you listening to this fellow ?|May I remind you:
{75633}{75696}He's wearing a costume,|not a uniform.
{75698}{75793}He's no more equipped to lead us|than this fellow. No offense.
{75824}{75885}Look, they're gone.
{75887}{75929}- Where'd they go, back inside ?|- I don't know.
{75931}{75999}- Nobody was watching .|- All right, all right !
{76001}{76072}Listen up. Here's the plan.|Gwen, Fred, Alex and I,|we'll go down and get a sphere.
{76074}{76123}Fleegman, you set up a perimeter,|and Tommy, you're lookout.
{76125}{76209}- You see anything at all,|you give us a signal.|- What kind of a signal ?
{76211}{76325}- Any kind of signal.|- Okay, I'll do my hands|like this, and caw, caw !
{76327}{76388}What are you, an infant ?|Look, we have these.
{76456}{76543}- That-- Sorry.|- All right, let's go.
{76710}{76797}- Does rolling help ?|- Uh-huh, it helps.
{76799}{76883}- Where's your gun ?|- It helps.|- Shoot !
{77069}{77116}- Oh.|- What ?
{77150}{77208}Never give up, never surrender.
{77210}{77256}Oh, shut up.
{77368}{77452}Run ! Run ! Run !
{77454}{77558}- They're everywhere,|they're everywhere.|- Everywhere !
{77560}{77623}- Come on, let's go.|- Let's go !
{77625}{77711}- Hurry !
{77713}{77804}They're everywhere.|Come on !
{77806}{77875}Don't look back. Don't look back.
{77877}{77931}- We're not gonna make it.
{77933}{77993}- Oh, God !
{77995}{78099}- I knew it, I knew it.|I knew this was gonna kill me.|- Hurry ! Go, go, go !
{78101}{78172}Come on. Push. Let's go. Go !
{78173}{78224}I got it, but it's gonna|take a few seconds.
{78226}{78267}I got it, I got it !
{78269}{78332}- Go ahead.|- There's no time. Get in, get in.
{78334}{78398}Of course, I forgot, you've got|to be the hero. Haven't you ?
{78400}{78472}Heaven forbid anybody else gets|the spotlight ! Oh, no, Jason Nesmith--
{78474}{78559}- Oh ! Jason ! Jason, come on !
{78561}{78646}- Hurry !|- Tommy, go ! Go ! I mean it !
{78648}{78759}Help ! No, no, no ! Jason, please !|Tommy, stop the pod, stop it !
{78761}{78855}- I can't stop it. It's on autopilot.|- Go ! Leave him !
{78857}{78903}No !
{79020}{79067}[ Screeching ]
{79120}{79167}Oh, right !
{79168}{79239}Of course, it's always|about you, isn't it ?
{79928}{80019}Oh, hey !
{80078}{80125}Gorignack, Gorignack.
{80127}{80222}- Gorignak, Gorignak,|Gorignak, Gorignak.
{80257}{80338}Jason ? Jason,|can you hear me ?
{80340}{80424}- Yeah, Gwen, you got me.|- Thank God. Are you okay ?
{80425}{80524}Yeah. As a matter of fact,|I've got Gorignak staring me|in the face right now.
{80525}{80610}But you know what ?|I think I can take him.
{80660}{80725}Jason, we're gonna use the digital|conveyor to get you out of there.
{80726}{80782}- The digital conveyor ?|- Yeah.
{80784}{80883}You gonna have me diced into cubes|and sent up there in a million pieces ?
{80885}{80950}- Right.|- Well, you know what ?
{80952}{81023}I think I'll take my chances|with Gorignak.
{81025}{81137}We're getting you out right now.|It's perfectly safe, isn't it, Teb ?
{81139}{81201}It has never been|successfully tested.
{81203}{81280}- What did he say ?|- Hold, please.
{81282}{81341}Theoretically, the mechanism|is fully operational.
{81342}{81428}However, it was built to accommodate|your anatomy, not ours.
{81430}{81497}But now that Tech Sergeant Chen|is here, he can operate it.
{81499}{81589}It was designed watching his motions|from the historical documents.
{81591}{81657}I-I-I mean, I can't.
{81659}{81717}- I-I can supervise.|- Jason, we're gonna test it.
{81718}{81794}- On what ?|- How about that pig lizard ?
{81796}{81904}- Hey, I'm doing all right|with the pig lizard.|- Please, Fred. And hurry.
{81980}{82063}I'm sorry. It's very exciting |to watch the master at the controls.
{82064}{82143}The operation of the conveyor is|much more-- hmm-mmm-- art than science.
{82144}{82217}Stand back, Jason.
{82265}{82329}Gorignak, Gorignak,|Gorignak.
{82798}{82870}- What ? What was that ?|- Uh--|- Nothing .
{82872}{82946}- I heard some squealing or something .|- Oh, no, everything's fine.
{82947}{82992}But the animal is|inside out.
{82994}{83068}I heard that.|It turned inside out ?
{83152}{83199}And it exploded.
{83201}{83303}Did I just hear that the animal|turned inside out and exploded ?
{83305}{83352}Hello ?
{83404}{83451}Hold, please.
{83452}{83499}Hey, wait a minute.|Guys, guys.
{83501}{83570}If the pig lizard is gone,|why are they still yelling "Gorignak."
{83571}{83656}Teb, hit|the translation circuit.
{83657}{83730}Gorignak, Gorignak. Rock.
{83732}{83811}Rock, rock, rock.
{83813}{83888}- Jason,
{83890}{83964}I don't think the pig lizard|was Gorignak.
{83966}{84024}What the hell|you talking about ?
{84251}{84298}Oh, darn.
{84565}{84609}Digitize me !
{84610}{84657}- Come on, Fred.|- Come on, guys, digitize me !
{84658}{84731}- Not me.|- Come on, they based it|on your hand movements.
{84733}{84779}- Am I the only one who saw|that thing inside out ?|- No, no, no, no.
{84781}{84827}I-I-I'm not the guy.
{84829}{84903}I'm not Tech Sergeant Chen.|Kwan's not even my real name.
{84905}{84954}Fred's no good, Jason.|You're just gonna have to kill it.
{84956}{85050}Kill it ? Well,|I'm open to any suggestions.
{85051}{85103}Go for the eyes,|like in episode 22 !
{85105}{85180}It doesn't have|any eyes, Tommy.
{85182}{85229}Go for the mouth or throat,|its vulnerable spots !
{85231}{85303}It's a rock.|It doesn't have any vulnerable spots !
{85305}{85383}I know ! You construct a weapon.|Look around you.
{85385}{85467}- Can you form some sort|of rudimentary lathe ?|- A lathe !
{85468}{85555}Get off the line, Guy ! Alexander,|you're my advisor. Advise me.
{85557}{85627}Well, you're just gonna have to|figure out what it wants.
{85629}{85675}What is its motivation ?
{85677}{85763}It's a rock monster.|It doesn't have motivation.
{85765}{85824}See, that's your problem, Jason.|You were never serious about the craft.
{85872}{85921}Oh ! Fred, can you hear me ?
{85923}{85984}Fred, are you there ?
{85986}{86056}- Kinda.|- You can do it, Fred. It's up to you.
{86058}{86131}Oh, no, no, no. Jason,|I'll just-- I'll just mess it up.
{86132}{86188}You did it for four years|on the show. Do it now.
{86190}{86256}That was the show.|I'm not that guy.
{86257}{86323}You never forgot a line.|You never missed a mark.
{86361}{86403}That's not me anymore, man.
{86456}{86535}It is you, Fred.|You just stopped trying .
{86588}{86657}You could do this, Fred. I know|in my heart, you're gonna save my life.
{86658}{86727}- I am ?|- No doubt about it, Fred.
{86729}{86782}Fred !
{86818}{86867}Fred, can you hear me ?
{86895}{86947}Fred !
{86949}{87044}Fred ?|I don't wanna die down here.
{87046}{87127}Digitize me, Fred !
{87187}{87246}- Oh, wow.|- Oh !
{87247}{87287}- Tech Sergeant Chen.|- Yeah !
{87390}{87472}Oh !
{87473}{87532}I see you managed|to get your shirt off.
{87636}{87695}- I did it.|- Welcome back, Fred.
{87697}{87784}All right, did we get|the beryllium sphere installed ?
{87786}{87878}- Yes, we are back to full power.|- Great. Engines and pods ?
{87880}{87958}- Fully operational.|- Perfect ! We'll crank this sucker up.
{87959}{88041}You can drop us off, and you guys can be|back to your home planet before supper.
{88043}{88099}Oh, no, sir,|we have no reason to go back.
{88100}{88156}Sure you do.|Family, friends. Come on.
{88158}{88219}We are all that is left.
{88364}{88455}- I didn't know that.|- Sir, I have raised the command deck.
{88551}{88633}Mathesar, meet us up|on the command deck.
{88635}{88696}Mathesar.
{88698}{88775}Mathesar, Quellek !
{88777}{88857}Why can't we reach them ?
{89323}{89429}Thank God, you're alive.
{89431}{89540}Now you will face justice,|Sarris.
{89541}{89666}At every turn, you demonstrate|the necessity for your extermination.
{89668}{89721}Leave him alone.
{89766}{89829}You wish to save the life|of this man ?
{89830}{89882}Yeah. Yes.
{89951}{90017}Then tell me--|what does it do,
{90018}{90123}- this Omega 13 ?|- I don't know what it does.
{90215}{90272}I said, I don't know.
{90315}{90383}- Is it a bomb ?|- I don't know.
{90385}{90455}- A booby trap ?|- I don't know !
{90456}{90520}- Tell me !|- I don't know !
{90522}{90590}- [ Moaning ]|- Do you think I'm a fool ?
{90592}{90701}That the commander does not know|every bolt, every weld in his ship ?
{90760}{90833}Prepare a tear harness...
{90835}{90881}for the female.
{90963}{91042}- You brute ! Let go of me !
{91043}{91095}I'm not the commander.
{91097}{91151}What did you say ?
{91152}{91230}I said,|I'm not the commander.
{91232}{91303}Leave them alone.|There's no reason to hurt them.
{91304}{91365}- They don't know anything .|- Explain.
{91367}{91505}Gwen, show him|the historical documents.
{91507}{91565}Computer,
{91566}{91669}show the historical documents|of the Galaxy Quest missions.
{92294}{92340}Wonderful.
{92410}{92541}You have all done far greater damage|than I ever could have.
{92542}{92594}Bravo !
{92596}{92660}Bravo.
{92662}{92722}This is a moment|I will treasure.
{92724}{92779}Explain to him...
{92781}{92879}who you all really are.
{92881}{92939}Tell him !
{92997}{93045}Explain !
{93127}{93177}Mathesar, the--
{93179}{93254}There's no such person|as Captain Taggart.
{93255}{93378}My name is Jason Nesmith.|I am an actor.
{93408}{93462}We're all actors.
{93464}{93551}He doesn't understand.
{93553}{93653}Explain as you would|a child.
{93728}{93818}We, uh--|We pretended.
{93933}{93985}We lied.
{93987}{94114}- Yes ! You understand that,|don't you, Mathesar ?
{94115}{94215}Mathesar, I--|I'm not a commander.
{94216}{94302}There's no National Space|Exploration Administration.
{94304}{94375}We don't have a ship.
{94377}{94456}But there it is.
{94510}{94557}That ship is that big.
{94558}{94638}But inside,|I see many rooms.
{94640}{94731}You've seen plywood sets|that look like the inside.
{94733}{94863}Our beryllium sphere is-is wire|with plaster around it.
{94865}{94934}And our--
{94935}{95005}our digital conveyor is...
{95006}{95075}Christmas tree lights.
{95077}{95136}It's a decoration.|It's all fake.
{95194}{95241}Just like me.
{95309}{95393}But why ?
{95438}{95484}It's difficult|to explain.
{95526}{95573}On our planet, we--
{95634}{95765}we pretend|to-to entertain and--
{95767}{95849}Mathesar,|I am so sorry.
{95851}{95918}God, I am so sorry.
{95920}{96015}- So now you know.
{96017}{96147}Lieutenant Lathe, hardwire|the reactor core to overload.
{96148}{96247}I would like to blow|this troublesome vehicle to dust.
{96248}{96315}- Sarris, what about my people ?|- Yes !
{96316}{96398}Far too simple|a death for them, isn't it ?
{96400}{96504}Lathe, open an oxygen seal|on level "C."
{96505}{96609}Let the air in a bit|for our friends.
{96611}{96688}Son of a--
{96753}{96821}Release them...
{96822}{96869}into space.
{96932}{97037}Core overload.|Emergency shutdown: overridden.
{97039}{97138}Core implosion estimated|in nine minutes.
{97140}{97272}- Core overload.|Emergency shutdown: overridden.|- Hey !
{97274}{97360}Where's the happy ending, Jason ?
{97398}{97472}Never give up,|never surrender.
{97614}{97737}Maybe it's about time you just backed|off, you fin-headed monstrosity.
{97738}{97811}- Jason ?|- You what ?
{97813}{97917}You're starting to act|like you did in episode 17,
{97919}{97970}you scene-stealing hack.
{98029}{98094}Oh, right.
{98096}{98172}Well, how does it feel, Jason ?
{98174}{98243}-Was it worth it ? You murdered us all !|-Shut up.
{98244}{98302}Hundreds to die|just because of you.
{98304}{98361}- I told you to shut up.|- Both of you, get in there.
{98363}{98434}Hundreds to die just because|you wanna play a big commander.
{98436}{98507}- You raving lunatic.|- Then I'll see you in hell, won't I ?
{98832}{98970}- Look out, Jason !|- Get his gun ! Get the gun !
{98971}{99026}Take that !
{99368}{99432}Sorry, I was-- Door was|a little sticky. Did you see that ?
{99434}{99505}I'll get one of my boys up here|with a can of WD-40.
{99602}{99680}- You used to pull your punches.|- Scene-stealing hack, thank you.
{99682}{99737}- Raving egomaniac.|- Can't think where I got that from.
{99739}{99787}Guys.
{99789}{99835}Look.
{99913}{99971}They're suffocating .
{100088}{100198}Core overload.|Emergency shutdown: overridden.
{100200}{100287}Core implosion estimated|in eight minutes.
{100321}{100422}General, your transport|is ready for departure !
{100538}{100643}Core overload.|Emergency shutdown: overridden.
{100645}{100727}Core implosion estimated|in seven minutes.
{100770}{100851}- Computer, shut down the core.|- Unable.
{100853}{100974}Memory checks invalid.|Core system's hardware damaged.
{100976}{101039}All right, listen up, this is what|we gotta do. Gwen, you and I,
{101041}{101099}we're gonna get to the core|and shut it down manually.
{101100}{101147}Fred, take Guy and Laliari.|You find that valve.
{101148}{101191}Shut it off before|those Thermians run out of air.
{101192}{101272}Alexander, get to the barracks. Wedge|a door open, in case they can't do that.
{101274}{101326}- Okay.|- Wait, Jason. What about me ?|What do I do ?
{101328}{101432}You're gonna practice driving .|Let's go !
{101434}{101480}Practice driving .
{101491}{101561}- So we get to shut down|a neutron reactor.|- That's right.
{101563}{101610}I hate to break it|to you, Jason,
{101612}{101678}but I don't know how to|shut down a neutron reactor,
{101679}{101733}and unless you took a learning annex|course I don't know about,
{101734}{101803}I'm pretty sure you don't know how|to shut down a neutron reactor either.
{101805}{101882}No, I don't,|but I know someone who does.
{101952}{102026}- Brandon, honey, garbage.
{102028}{102086}Aw, Mother,|I'm quite busy.
{102087}{102145}Come on, Brandon,|don't make me ask you again.
{102147}{102244}Just ten more minutes.|Okay, Ma, I promise.
{102274}{102320}Great.
{102546}{102642}- Hello ? Anybody there ?
{102680}{102735}Hello ?
{102737}{102783}Hello ?
{102785}{102879}Got him. Listen to me.|This is Jason Nesmith.
{102881}{102983}I play Commander Peter Quincy Taggart,|N.S.E.A. Protector.
{102985}{103078}We accidentally traded boxes the other|day when we bumped into each other.
{103079}{103191}Oh ? Oh.|Commander, I see.
{103193}{103264}- Okay.|- What's your name, son ?
{103266}{103328}[ Sighs ]|Brandon.
{103329}{103397}Brandon, I remember you|from the convention, right ?
{103398}{103485}You asked all those little|technical questions about the ship,
{103487}{103534}and I was a little short|with you.
{103536}{103629}Yes, yes, I know, Commander,|and I actually wanna--
{103631}{103713}I just wanted to tell you that|I-I thought a lot about what you said.
{103714}{103781}- It's okay. Listen.|- But I want you to know...
{103782}{103866}that I'm not a complete|brain case, okay ?
{103868}{103939}I understand completely|that it's just a TV show.
{103940}{103992}- H-Hold-- Wait a minute.
{103994}{104089}Stop for a second.|Stop. Wait. It's all real.
{104091}{104186}Oh, my God, I knew it.|I knew it ! I knew it !
{104188}{104270}The crew and I are in a lot of trouble,|and we need your help.
{104299}{104403}Core overload.|Emergency shutdown: overridden.
{104405}{104482}Core implosion estimated|in six minutes.
{104563}{104625}Sir, it's you.|Thank Ipthar.
{104665}{104737}Quellek ?|What are you doing up there ?
{104798}{104891}I avoided capture by using |your Mak'tar stealth face.
{104893}{104963}- Where is everyone ?|- Come with me.
{104965}{105023}I'll explain on the way.
{105088}{105143}All right, we're at level "C,"|hallway five. Now what ?
{105144}{105259}Um, go to weapons storage,|your second left, through the passage.
{105260}{105335}And that leads to a system|of utility corridors|through the bowels of the ship.
{105337}{105402}- Open.|- You know, I'm gonna get Kyle.
{105404}{105471}He knows the utility tunnel system|better than anybody alive.
{105523}{105569}...38, 39, 40.
{105629}{105705}All we have to do is|turn off the valve to the barracks.
{105847}{105909}- Hi, Brandon.|- No time for pleasantries, Kyle.
{105911}{106006}We have a level five emergency.|You still got the utility systems|walk-through, right ?
{106007}{106095}Yeah, I've got sectors|one through twenty-eight.|Hollister has the upper levels.
{106096}{106144}Great.|We'll get everybody on-line.
{106333}{106460}- Pedal to the metal, Commander.|- Pedal to the metal, Commander.
{106499}{106556}General !|I have just received word...
{106558}{106621}that the commander of the Protector|and his command crew...
{106623}{106675}have escaped custody.
{106677}{106722}What ?
{106778}{106904}- Find them !|- But sir ! My men--|The core implosion--
{106906}{106961}Find them !
{107001}{107079}All right, Brandon, I see five ducts|in this room. Which way do we go ?
{107080}{107130}Enter the passage|second to your left...
{107132}{107205}and just continue straight|for 50 meters.
{107207}{107284}Ducts ?|Why is it always ducts ?
{107286}{107334}- Ah, there will be a slight drop.
{107515}{107602}Thanks for the heads-up,|Brandon ! You okay ?
{107722}{107786}They're dying .
{107788}{107849}- Wait a minute.|We gotta go across this thing ?|- Yes.
{107851}{107946}- Don't look down.|- What I'd give to see|what you're seeing .
{107947}{108042}- What are you talking about ?|- You're deep in the underbelly|of the Omega 13 !
{108043}{108113}Oh, it must be spectacular.
{108115}{108183}It-It doesn't look|like much to me.
{108184}{108324}There's just these few walls|and this dumb spinning fan|that we have in every single--
{108633}{108735}Brandon, what does|the Omega 13 device do ?
{108737}{108814}Uh, many have believed|that it is a matter collapser.
{108816}{108918}A bomb capable of destroying pretty much|everything in about 13 seconds.
{108919}{108999}- But myself and others are convinced|that what it is...|- I'm gonna go. Go.
{109001}{109057}is a matter rearrange,
{109059}{109123}affecting a 13-second time jump|to the past.
{109125}{109240}Why 13 seconds ?|That's really not enough time|to do anything of any importance.
{109241}{109331}- It'd be time to redeem|a single mistake.|- What ?
{109333}{109441}- Go, go, go, go !
{109447}{109521}We-We gotta turn off that valve.|Their oxygen's almost gone.
{109550}{109598}Listen.|I'll go in.
{109600}{109663}I'll create a distraction.|I've got this. I'm okay.
{109665}{109734}I'm gonna be able to hold him back|long enough for the aliens to escape.
{109735}{109820}- That's suicide.|- I'm just a glorified extra, Fred.
{109822}{109913}I'm a dead man anyway. If I'm gonna die,|I'd rather go out a hero than a coward.
{109915}{110014}Guy, Guy, maybe you're|the plucky comic relief.
{110015}{110062}You ever think|about that ?
{110092}{110138}- Plucky ?|- Oh, besides,
{110140}{110223}I just had this|really interesting idea.
{110225}{110274}Are you stoned ?
{110276}{110350}Gotta get her up|and give them some time.
{110352}{110421}- Sir, perhaps together--
{110423}{110502}the Mak'tar chant of strength:|Larak tarath.
{110504}{110578}- Larak tarath, larak tarath.|- Larak tarath.
{110580}{110684}[ Together ] Larak tarath, larak tarath,|larak tarath, larack tarath.
{110888}{110950}All right, Brandon, we're across.|Now what ?
{110951}{111049}You wanna take a left and then just|straight on through the chompers.
{111051}{111093}"The chompers" ?
{111221}{111300}- Well, screw that.|- How are we supposed|to get through this ?
{111302}{111353}Hollister, do you have|the sequence yet ?
{111355}{111409}Okay, the sequence is...
{111411}{111478}two-two-four-two--
{111480}{111554}What is this thing ?|I mean, it serves no useful purpose...
{111556}{111639}for there to be a bunch|of chompy, crushy things|in the middle of a hallway !
{111641}{111734}We shouldn't have to do this.|It makes no sense ! Why is it here ?
{111736}{111801}- 'Cause it's on the television show.|- Well, forget it !
{111803}{111886}I am not doing it !|This episode was badly written !
{111888}{111942}Okay, Commander, now, as soon|as the first crusher hits you--
{111943}{111990}- It just did !
{111991}{112046}- Okay, go now.|- Go !
{112047}{112119}Go ! Stop !
{112121}{112192}Go !|Wait a minute.
{112194}{112260}Come on,|come on, come on.
{112295}{112362}Go ! Go !
{112364}{112411}Go ! Go !
{112413}{112483}- Go !|- Stop, stop. Go !
{112485}{112531}- Stop !
{112533}{112589}Jump, Commander, jump !
{112590}{112679}Whoever wrote this episode|should die !
{112722}{112768}This should be interesting .
{113257}{113318}It's the simple things in life|you treasure.
{113357}{113403}That's great.
{113487}{113538}Now, we better get--
{113645}{113691}Get a room, guys.
{113740}{113793}Whoa !
{113872}{113919}Hey, Fred.
{113969}{114030}Hey, Fred, uh--
{114088}{114186}Oh, that's not right.|Oh !
{114851}{114936}Sir, the pressure--|it's normalizing .
{114976}{115023}All right !
{115060}{115128}We are saved.
{115130}{115177}He has saved us.
{115179}{115268}Commander Taggart|has saved us !
{115389}{115436}It's just not fair.
{115489}{115579}All right, Quellek,|let's get back to the commander.
{115581}{115634}[ Laser Blast ]
{115636}{115714}I'm-I'm shot.
{116095}{116181}- Quellek ?
{116284}{116331}That's not too bad.
{116332}{116413}We'll get you to the medical quarters,|and you'll be fine.
{116415}{116488}It has been my greatest honor|to serve with you.
{116490}{116582}I have been blessed, sir.|I-I--
{116584}{116635}Don't speak, Quellek.
{116746}{116798}You'll forgive|my impertinence, sir,
{116800}{116858}but even though|we had never before met,
{116859}{116954}I always considered you|as a father to me.
{117015}{117087}Quellek.
{117111}{117177}By Grabthar's hammer,
{117179}{117259}by the sons of Warvan,
{117260}{117388}you shall be avenged.
{118281}{118371}...13, 14, 15, 16,|17, 18, 19 !
{118373}{118460}- All right, Brandon,|how do we shut this thing down ?|- Okay, just push the blue button.
{118461}{118521}- The blue button-- is that it ?|- Yeah, why ? What's wrong ?
{118523}{118594}Nothing . I just thought it'd be|more complicated than that.
{118635}{118730}Core implosion estimated|in 20 seconds.
{118959}{119034}Brandon, it's not working .|Brandon !
{119100}{119149}Mother, I cannot stress enough|the severity...
{119151}{119235}- of the commander's predicament.|- Don't forget the recyclables !
{119236}{119331}Core implosion estimated|in ten seconds.
{119363}{119408}- Nine, eight,|- Gwen, I--
{119410}{119456}- seven, six,|- I've always--
{119458}{119526}- five, four,|- Jason, oh, Jason.
{119528}{119597}three, two, one.
{119837}{119914}- It always stops at one on the show.
{119915}{119968}Um, what were you saying ?
{119971}{120016}- Sir !|- What ?
{120018}{120071}The core detonation sequence|on the Protector has been aborted.
{120073}{120127}Impossible !|Impossible !
{120128}{120239}Lock a complement of implosion missiles|under the Protector.
{120240}{120328}Tear her apart.
{120561}{120669}He's finished. Alexander,|listen to me. It's okay, it's okay.
{120671}{120728}The Thermians can handle it from here.|We gotta go. Come on.
{120777}{120839}We need that armor|back up !
{120841}{120953}- Get me a forward view right now !|- Plasma armor: engaged.
{120955}{121039}- All right, Tommy, see if you can|lose 'em in that mine field.
{121041}{121107}- M-Mine field ?|- Pedal to the medal, right now !
{121108}{121159}- Pedal to the medal !|- All right, let's go !
{121397}{121458}Good going, Tommy.|Great going .
{121460}{121517}Thrust ahead-- full !
{121519}{121607}Into the field !|Go !
{121723}{121841}- Tommy, can you get us closer|to these mines ?|- Closer ?
{121940}{121987}I could try.
{122114}{122192}General,|I've lost them.
{122194}{122300}The magnetism of the mine field|is disrupting our instruments.
{122301}{122378}Wait !|I see something .
{122380}{122459}Yes. Yes !|There they are.
{122461}{122525}- Get back on their tail.|- I can't, sir.
{122526}{122617}- What ? Why not ?|- Because they're coming right at us.
{122619}{122674}Fire at will.
{122778}{122881}Whoo ! We're getting hammered,|Jason ! Return fire ?
{122883}{122950}No ! Divert all energy|to the armor !
{122951}{123007}How adorable--
{123008}{123078}the actors are going |to play war with me.
{123080}{123195}- Sarris' ship, accelerating |toward us at mark 2.|- Accelerate to mark 4.
{123297}{123384}Let me remind you, sonny:
{123386}{123446}I am a general.
{123448}{123519}If you are counting on me|to blink,
{123521}{123610}then you are making |a deadly mistake.
{123612}{123696}Well, let me tell you|something, Sarris.
{123698}{123816}It doesn't take a great actor to|recognize a bad one. You're sweating .
{123818}{123875}Armor almost gone, Jason !
{123876}{123998}You fool ! You failed to realize|that with your armor gone,
{124000}{124111}my ship will tear through yours|like tissue paper.
{124112}{124234}And what you fail to realize is|my ship is dragging mines.
{124291}{124356}Oh, no !|Turn, turn !
{124745}{124791}- We did it !
{124829}{124879}Yes ! Yes !
{124881}{124927}- Yes !
{124957}{125014}Yes ! Yes !
{125039}{125177}- Mathesar !
{125219}{125293}- Oh, my God, you're alive.
{125295}{125411}- Come here.|- The ship was a model as big as this.
{125412}{125476}A very clever|deception indeed.
{125704}{125750}Set a course|for home, Commander ?
{125752}{125825}- Can you do that ?|- Oh, yeah, just point and click.
{125826}{125898}- But we're gonna have to go|through the black hole.|- Any objections ?
{125947}{126017}All right, set her up.
{126096}{126143}What's the matter,|Mathesar ?
{126185}{126261}We were hoping |you could come with us.
{126263}{126357}M-My people|have no commander.
{126359}{126431}Mathesar, I think your people...
{126433}{126501}have a great commander.
{126726}{126798}All right, Tommy,|take us into the black hole.
{127180}{127238}- We're out !|- We're going home.
{127240}{127339}- Systems register functional.|- All systems are working, Commander.
{127341}{127446}Jason, before the black hole, there was|an energy surge from Sarris' ship.
{127448}{127546}Let's not worry about that|right now, Alexander.|Fred, what are you doing up here ?
{127548}{127662}Shouldn't you be downstairs|until we dec-- Hey, you can put|an eye out with that thing .
{127724}{127777}Fred ?
{128152}{128206}No !
{128788}{128890}Mathesar ! Activate|the Omega 13 !
{129468}{129541}- We're out !|- We're going home !
{129568}{129623}Systems register functional.
{129625}{129671}All systems are working ,|Commander.
{129673}{129780}Jason, before the black hole, there was|an energy surge from Sarris' ship.
{129814}{129922}Jason, what are you doing ?|What are you doing ?
{129958}{130018}Let go of me. Let--|It's not Fred.
{130020}{130115}That's Sarris. Listen to me.|I'm telling you, that's not Fred,|that's Sarris.
{130117}{130175}He's gonna try to kill|all of us.
{130371}{130436}Never give up,|never surrender.
{130477}{130555}Jason. Jason !|I can't slow it down !
{130557}{130620}Our ship is too big|to enter the atmosphere.
{130622}{130686}We need to separate,|or we'll die.
{130797}{130858}We gotta do it.|It's our only hope, Mathesar.
{130860}{130906}Thank you.
{130908}{130967}Crew to|the secondary deck.
{131007}{131078}Mathesar !
{131129}{131188}Good-bye, my friends.
{131316}{131408}Fred, get up to command deck.|We're separating .
{132021}{132079}On, Teb, on !
{132259}{132317}This is the third day|of the Galaxy Con,
{132319}{132421}and Jason Nesmith and his entire crew|are no-shows here at the big event,
{132423}{132496}much to the disappointment|of all these fans, knows as Questoids.
{132498}{132581}- Bye. Be back soon.|- Wait a minute. Where you going |with those fireworks ?
{132583}{132679}Well, the Protector|got super accelerated|coming out of the black hole,
{132681}{132737}and it nailed the atmosphere|at mark 15,
{132738}{132806}which, you guys know,|is pretty unstable obviously,
{132808}{132888}so we're gonna help Laredo guide it|on the vox ultra-frequency carrier...
{132890}{132948}and use Roman candles|for visual confirmation.
{132949}{133014}A-All right,|dinner's at 7:00.
{133090}{133172}- Well, he's outside.|- Hmm.
{135273}{135351}Lieutenant Laredo--|Tommy Webber !
{135393}{135456}Hi, Tommy !
{135506}{135590}The beautiful Tawny Madison--|Gwen DeMarco !
{135592}{135685}Yes ! Yes !
{135714}{135765}Wow, what effects !
{135767}{135886}Another shipmate !|Yes, the more, the merrier !
{135921}{136039}The ship's Tech Sergeant Chen,|Fred Kwan, and a friend.
{136040}{136149}Dr. Lazarus--|Alexander Dane !
{136151}{136223}Give a big hand.|He's British !
{136224}{136283}Yes, sir !
{136285}{136384}Commander Peter Quincy Taggart--|Jason Nesmith !
{136569}{136633}Great driving, Tommy.
{136635}{136681}Yeah ! Yes !
{136883}{136935}Quick, quick, quick.
{137208}{137273}Mr. Jason Nesmith !
{137311}{137436}Come on, give it up for the crew,|the N.S.E.A. Protector !
{137437}{137541}Ah, true love !|Yes !
{137569}{137618}Wow !
{137744}{137799}They're here for you folks.|Give it up !
{137801}{137847}What a show !
{137902}{137962}What a show ! Yes !
{138019}{138079}Yes ! Yes !
{138139}{138197}Come on, give it up !|Give it all up...
{138199}{138273}for the crew of your favorite show,|Galaxy Quest !
{138275}{138321}Wow !
{138384}{138441}Come on, come on !
{138671}{138761}Don't forget to buy Galaxy Quest|T-shirts on your way out.
{138763}{138809}Thank you.
{138811}{138856}Whoo !
{138923}{138983}And now,|back again after 18 years,
{138984}{139055}the New Adventures of Galaxy Quest.
