{1212}{1301}- Exiting the time knot now, sir.|- We're alive !
{1303}{1364}We made it, Commander.|We made it.
{1366}{1464}By Grabthar's hammer,|we live to tell the tale.
{1466}{1533}[ Computerized Voice ]|Systems registering functional.
{1535}{1597}All systems are|working, Commander.
{1599}{1705}I don't like it.|It was too easy.
{1707}{1837}- [ Boy ] Wait ! Oh, no.|They're everywhere !|- [ Alarm Blaring ]
{1839}{1920}- There are time knots|opening everywhere !|- A trap !
{1922}{1996}We're surrounded,|Commander.
{2037}{2136}- Aah !|- Ooh !
{2138}{2205}It's a core meltdown, sir.|It can't be stopped.
{2207}{2291}Surrender may be|our only option.
{2293}{2360}No ! Never give up !
{2362}{2420}Never surrender !
{2422}{2492}Your orders, sir ?
{2547}{2619}Sir ?|Group orders ?
{2691}{2780}Activate the Omega 13.
{2828}{2923}- [ Audience Applauding ]|- [ Man ] Well ?
{2925}{3046}Huh ?|Well, there you are.
{3048}{3129}- Yeah ! Huh ?|- [ Audience Cheering, Applauding ]
{3165}{3306}Yeah ! Yeah, that's|what I'm talking about.
{3308}{3446}You are the first people|to see the lost Galaxy Quest--
{3448}{3535}episode 92|two-parter--
{3537}{3614}since it was originally aired|in 1982 !
{3616}{3728}- Huh ? Yeah ! All right.|- [ Audience Applauding ]
{3730}{3819}And now, the moment you've|all been waiting for--
{3821}{3977}the intrepid crew|of the N.S.E.A. Protector !
{3979}{4037}- Yeah ! Yeah !|- [ Crowd Cheering ]
{4039}{4186}[ Man ]|Red scarf, black shoes. Wait.
{4188}{4326}White scarf, black buttons,|white shoes.
{4385}{4470}Man, where in the hell is he ?|An hour and a half late ?
{4472}{4566}- An hour and a half.|- I mean, this is unreal.
{4568}{4638}They're gonna start|eating each other out there.
{4640}{4740}Oh, did you hear ? He booked|another appearance without us.
{4742}{4801}You're kidding.
{4847}{4939}Oh. Uh--|Um--
{5047}{5115}- How did I come to this ?|- Not again.
{5117}{5204}- I played Richard the Third.|- Five curtain calls.
{5206}{5302}There were five curtain calls.|I was an actor once, damn it !|Now look at me. Look at me !
{5304}{5372}I cannot go out there,|and I won't say...
{5374}{5489}that stupid line|one more time !
{5491}{5584}- I can't, I won't.|- Well, Alex, at least you had a part.
{5586}{5657}Okay ? You had|a character people loved.
{5659}{5747}I mean, my TV Guide interview|was six paragraphs...
{5749}{5836}about my boobs and how they|fit into my suit.
{5838}{5934}No one even bothered to ask me|what I do on the show.
{5979}{6092}You had the-- Wait.|Wait, I'll think of it.
{6094}{6194}- I repeated the computer, Fred.|- Whew !
{6196}{6297}Your commander is on deck !|Ha, ha !
{6299}{6384}Wow, that smog|is thick today, huh ?
{6386}{6472}- Am I too late for|Alexander's panic attack ?|- [ Objects Clattering ]
{6474}{6562}Apparently not. You know,|you should get that looked at.
{6564}{6652}[ Chuckles ]|Yeah.
{6654}{6733}[ Emcee in Distance ]|Let's take a look at a few more clips.
{6735}{6847}Okay.|What did I do ? Hmm ?
{6849}{6915}- [ Audience Chanting ]|We want the crew !|- What ?
{6917}{7029}- [ Chanting ] We want the crew !|- For those four seasons,|we developed the same affection...
{7031}{7131}for the crew as the crew|had for each other.
{7133}{7223}These weren't just adventurers|exploring space.
{7225}{7284}- Friends.|- These were friends.
{7286}{7370}- Unbelievable.|- You are so full of it, man !
{7372}{7446}It's not a big deal ! These guys|put a little set in their basement.
{7448}{7555}I'm there about an hour.|It's nothing, Gwen.
{7557}{7608}They wanted|the Commander.
{7610}{7701}- There he goes.|- Alexander, wait a minute.|Grab him ! Grab him !
{7703}{7796}- We want the crew ! We want the crew !|- [ Emcee ] Okay !
{7798}{7882}Yeah !|Here we go !
{7884}{7963}Come on, old friend.|Old friend.
{7965}{8055}You stole all my best lines.|You cut me out of episode two entirely.
{8057}{8166}- Excuse me.|- [ Emcee ] Tawny Madison--|my personal favorite--
{8168}{8240}- Gwen DeMarco !|- [ Crowd Cheering ]
{8242}{8297}Yeah !
{8368}{8452}Yeah, that's what I'm talkin' about !|Let's hear a warm welcome...
{8454}{8594}for crack gunner Laredo--|Tommy Webber !
{8640}{8701}- You will go out there !|- I won't,
{8703}{8761}and nothing you say|will make me.
{8763}{8882}- The show must go on.|- [ Emcee ] Freddie Kwan !
{8937}{9004}- Damn you.|- [ Emcee Continues, Indistinct ]
{9006}{9137}Damn you. I won't say|that stupid line one more time.
{9139}{9252}Tev'Meck--|Alexander Dane !
{9254}{9312}Yeah !|All right !
{9314}{9396}[ Crowd Cheering ]
{9398}{9533}By Grabthar's hammer,|you shall be avenged !
{9535}{9637}Yeah !|All right !
{9639}{9734}That guy can act.|And finally,
{9736}{9818}my-- my fellow|Questerians,
{9820}{9960}the brave Commander|of the N.S.E.A. Protector,
{9962}{10028}Peter, Peter, Peter,|Peter, Peter,
{10030}{10146}Quincy, Quincy, Quincy, Quincy,|Taggart, Taggart, Taggart Taggart--
{10148}{10275}- Jason Nesmith ! Yes !|- [ Crowd Cheering ]
{10435}{10511}[ Woman ]|We love you, Commander !
{10562}{10667}- Never give up, never--|- [ Audience In Unison ]|Never surrender !
{10669}{10782}Damn the resonance cannons,|full speed ahead ! Huh ?
{10867}{10963}[ Emcee ] The Commander and his crew|will be signing autographs...
{10965}{11072}on Imperial decks "C" and "B"|near the Coke machines.
{11074}{11192}[ Man ]|Whoo ! Quest forever, man !
{11205}{11269}Excuse me, pardon me.|Crew member coming through.
{11271}{11354}- Fans, right ? Hey, Gwen.|- Oh, hey, man.
{11356}{11422}I want to thank you for that|nice intro you gave us today.
{11424}{11500}- Um--|- Guy.
{11502}{11570}You probably don't remember me,|do you ? It's the sunglasses, right ?
{11572}{11652}I was on the show in '82,|episode 81.
{11654}{11780}Got killed by a lava monster|before the first commercial. Aaah !
{11782}{11922}Listen, uh-- Maybe I could sit in|and, uh, sign a couple autographs ?
{11924}{12047}By Grabthar's hammer, by the sons|of Warvan, I shall avenge you !
{12209}{12346}- By Grabthar's--|- Next.
{12348}{12460}Had I moved an inch to the left,|the beast would have killed me.
{12462}{12556}- On the other hand,|my crew was in danger.|- How did you know what to do ?
{12558}{12686}Come on ! Without my crew,|I'm not a commander, huh ?
{12688}{12782}I think we all remember what happened|to that beast on Enok Seven, right ?
{12784}{12854}[ Crowd Laughing ]
{12856}{12972}You've gotta admit,|they really do love him.
{12974}{13044}Yeah, almost as much|as he loves himself.
{13108}{13190}Excuse me, Commander.|Hey !
{13192}{13344}I was wondering if you|could help settle a dispute|my crew and I seem to be having.
{13346}{13433}Um, if you remember, uh,|in "Quasar Dilemma--"
{13435}{13515}Excuse me|for a minute, fellas.
{13576}{13640}I hadn't even gotten|to the relevant conundrum.
{13642}{13735}In episode 15,|"Mist of Delos Five,"
{13737}{13861}I got the feeling that you and|the Commander kind of had a thing.
{13863}{13937}- Did you ?|- No.
{13939}{14003}The Commander and I|never had a thing.
{14005}{14089}Well that's|her story.
{14205}{14298}Excuse me.
{14300}{14410}Gwen. Gwen.
{14478}{14536}Gwen.
{14568}{14626}- Commander.|- Excuse me.
{14628}{14697}I must speak to you.|It is a matter of supreme importance.
{14699}{14778}We are Thermians|from the Klatu Nebula...
{14780}{14841}and we... need your help.
{14843}{14905}Oh, oh, oh.
{14907}{14965}Is this about|that gig tomorrow ?
{14967}{15069}Just hammer out the details|with my agent, and make sure|there's a limo at my house.
{15071}{15193}Last time I did one of these gigs,|they shoved me in the back of a Toyota.
{15195}{15277}Remember,|mum's the word.
{15279}{15360}- Certainly, but um--|- Mum.
{15362}{15445}- Mum. Mum.|- Mum.|- Mum.
{15447}{15559}Look here.|And... beautiful.
{15643}{15730}Crewman Madison.|The mist of this strange planet...
{15732}{15830}is filling my head|with such thoughts.
{15832}{15925}It was cute when I|didn't know you.
{16014}{16084}[ Chuckles ]|You--
{16121}{16232}- [ Chattering, Indistinct ]|- [ Laughing ]
{16234}{16292}[ Giggling ]
{16434}{16521}[ Man Coughing ]
{16680}{16740}[ Men Chuckling ]
{16742}{16876}What a freak show, man.|Oh, this is hilarious.
{16878}{17002}Bunch of losers ! Beggin'|for autographs at 15 bucks a pop.
{17004}{17080}- [ Toilet Flushes ]|- These guys haven't had|a real acting job for 20 years.
{17082}{17166}- This is all they've got.|- Did you check out Nesmith ?
{17168}{17258}He actually gets off on those retards|thinking he's a space commander !
{17260}{17321}- Yeah ! Oh, and his friends ?|- I know !
{17323}{17407}They can't stand him ! Did you|hear them ragging on him in there ?
{17409}{17511}Dude, he has no idea he's|a laughingstock, even to his buddies.
{17513}{17590}- He's pathetic !|- Ooh, come on, come on.
{17592}{17650}The Galaxy Quest Dancers|are almost on.
{17652}{17747}Whoo ! Full speed ahead,|Lieutenant.
{18123}{18221}Hey, Commander,|uh, so, as I was saying,
{18223}{18299}in "The Quasar Dilemma," remember,|you used the auxiliary of deck B--
{18301}{18384}could you get this--|deck B for gamma override.
{18386}{18467}The thing is is that|online blueprints clearly indicate...
{18469}{18560}that deck B is independent|of the guidance matrix.
{18562}{18656}So, we were wondering|just where the error lies in that.
{18658}{18766}It's just a television show.|That's all, okay ?
{18768}{18826}[ Chuckles ]|Right, but--
{18828}{18895}'Cause we were wondering if the quantum|flux-- Now, just listen on this--
{18897}{18968}There is no|quantum flux !
{18970}{19104}There's no auxiliary.|There's no goddamn ship !
{19106}{19183}You got it ?
{19221}{19339}- [ Crowd Murmuring ]|- [ Man ] Where's he going ?
{19481}{19543}I mean it.|I mean it, Alex.
{19545}{19635}I've never seen him lose it like that.|Not to a fan.
{19637}{19695}I mean, it was|just weird.
{19697}{19831}Gwen, I have|said it for years.
{19833}{19892}He's mentally unstable.
{19894}{19977}[ Sighs ]|l-- I'm worried.
{19979}{20042}It just was not|like him.
{20055}{20147}[ TV: Man Grunting ]
{20149}{20256}[ TV: Gunfire ]
{20551}{20624}[ Channels Changing ]
{20626}{20717}As long as there|is injustice,
{20719}{20810}whenever a Targathian baby|cries out,
{20812}{20906}- wherever a distress signal|sounds among the stars,|- [ Reciting Along ]
{20908}{21041}-we'll be there-- this fine|ship, this fine crew.|-This fine ship, this fine crew.
{21043}{21141}- Never give up and never surrender.|- Never give up.
{21143}{21224}Never surrender.
{21563}{21640}[ Knocking ]
{21741}{21850}- [ Knocking Continues ]|- [ Moaning Softly ]
{22163}{22226}[ Groans ]
{22896}{23018}- Can I help you ?|- Sir, I understand this is|a terrible breach in protocol--
{23020}{23113}- You guys shouldn't come|to my house, man.|- I beg you to hear our plea.
{23115}{23192}We are Thermians|from the Klatu Nebula.
{23194}{23291}Our people are being systematically|hunted and slaughtered...
{23293}{23351}by Roth'h'ar Sarris|of Fatu-Krey.
{23353}{23494}We are to meet in negotiation.|However, our efforts in this|regard have been disastrous.
{23496}{23640}Please, Commander.|You are our last hope.
{23642}{23716}[ Chuckles ]
{23718}{23806}- We have secured our limousine.|- What ?
{23808}{23891}Oh, oh, oh, oh.
{23893}{24015}Um, it's the thing|for the thing that's, um--
{24077}{24160}[ Chuckles ]|Maybe I should get some pants on.
{24218}{24276}Come on in.
{24379}{24448}- [ Groans ]|- Commander,
{24450}{24531}I must say that standing here|in your presence...
{24533}{24670}is the greatest honor we could have|ever hoped to achieve in our lifetimes.
{24672}{24748}That's-- I really|appreciate that.
{24750}{24840}Would you guys look for another shoe|that looks like this, please ?
{24842}{24942}[ Groans ]
{25133}{25224}Sir, I am Lahnk,|senior requisition officer.
{25226}{25327}Before we travel to the ship, please let|me know if you have any requirements.
{25329}{25456}- Weapons, documents, personnel ?|- Um, a Coca-Cola ?|Do you have one of those ?
{25508}{25600}- Sir, I am Teb.|- [ Chuckles ]
{25602}{25660}I would like to explain|the history between our people...
{25662}{25770}- and the Sarris Dominion|in greater detail.|- Hey, how ya doin' ?
{25772}{25884}In the five million years|following the Great Nebula Burst,
{25886}{26004}- our people were one p--|- What's your name ?
{26006}{26117}- Doesn't she talk ?|- Her translator is broken.
{26119}{26201}[ Shrieks ]
{26203}{26264}- [ Opens Soda Can ]|- Okeydokey.
{26266}{26410}You know, guys, I had a late night|with a Kreemorian Fangor beast,
{26412}{26540}so I'm gonna just|shut my eyes for a bit.
{26542}{26667}Go on. You know. I'm listening|to everything you say, okay ?
{26669}{26751}In the five million years|following the Great Nebula Burst,
{26753}{26817}our people|were one people.
{26819}{26946}But then came the Zactor Migration,|and then the Melosian Shift,
{26948}{27106}dark period of discontent|once spread through the land.
{27108}{27239}Fighting among Treeb sects|and Largoths-- ah, the foolishness.
{27241}{27331}And it was in this time|of dissension that Sarris--
{27383}{27451}[ Barking ]
{27560}{27652}- [ Laliari ] Commander. Commander.|- Hmm.
{27654}{27790}I'm sorry to wake you, sir,|but your presence is requested|on the command deck.
{27888}{27946}[ Grunts ]
{27948}{28012}- Sir, Sarris has moved the deadline.|- [ Groans ]
{28014}{28108}We are approaching his ship|at the Ni-delta now.
{28110}{28168}He wants an answer|to his proposal.
{28170}{28249}Yeah, I got most of it in the car.|Sarris is the bad guy, right ?
{28251}{28331}Oh, yes, sir.|He's a very bad man indeed.
{28333}{28431}He has tortured our scientists, put us|to work in the gallium arsenide mines,
{28433}{28515}- Mm-hmm.|- captured our females|for his own demented purposes--
{28517}{28614}Yeah, yeah, I got the picture.|Do you have pages or do you|just want me to wing this ?
{28616}{28686}- I am not sure I understand you.|- [ Mathesar ] Commander.
{28688}{28762}- Welcome to the Protector Two.|- Good to see ya.
{28764}{28854}- Would you like to don your uniform ?|- I'd like to skip that.
{28856}{28945}I got this gig in Van Nuys in about a|quarter of an hour. Is that all right ?
{28947}{29044}- As you wish.|- Sir, it's Sarris.
{29046}{29104}He's here.
{29283}{29399}General, I just received word|the Thermians have appointed|a new commander...
{29401}{29481}to handle|the negotiations.
{29483}{29541}What ?
{29543}{29621}[ Moaning ]
{29674}{29794}This is great. You know, usually|it's just cardboard walls in a garage.
{29796}{29888}- Sir, we apologize|for operating in low-power mode,|- Oh. Oooh.
{29890}{30041}but we are experiencing|a reflective flex field|this close to the galactic axis.
{30043}{30179}You know what I could use ?|A cup holder and a couple of Advil.
{30181}{30251}We're approaching in five ticks, sir.|Command to slow ?
{30253}{30331}Set it on screen saver two.
{30376}{30462}[ Chuckles ]|Because we, you know-- We gotta--
{30464}{30564}[ Groans ] Oh, I'm sorry|to break the mood here.
{30566}{30660}Um, slow it down|to mark two, Lieutenant.
{30662}{30720}[ Sarris Over Speaker ]|I see fear.
{30722}{30813}- That is expected.|- Mm-hmm.
{30815}{30939}- Ahh, they bring a new commander.|- It's good.
{30941}{31009}- Here are my demands.|- It's scary.|I mean, you know, he looks...
{31011}{31092}- And if I do not hear what I like,|- real.
{31094}{31164}then there will be blood...
{31166}{31300}and pain|as you cannot imagine !
{31302}{31377}- First, I require...|- Backwash.
{31379}{31448}the Omega 13.
{31450}{31589}Second, I will require|a technician--
{31591}{31748}Okeydokey. Let's fire blue particle|cannons full. Red particle cannons full.
{31750}{31842}Gannet magnets,|fire them left and right.
{31844}{31915}And let 'em run all chutes.|And while you're at it,
{31917}{31976}why don't you toss that|at 'em, killer ?
{31978}{32056}That should take care of|old lobster head, shouldn't it ?
{32058}{32106}[ Chuckles ]
{32345}{32400}Commander,|where are you going ?
{32402}{32463}- Home.|- You-- You mean Earth ?
{32465}{32523}Yeah, Earth. I need|to get back to Earth, kids.
{32525}{32612}But the negotiation.|You-You fired on him.
{32614}{32702}- Yeah, yeah. Long live--|What was your planet called ?|- Thermia.
{32704}{32806}- Long live Thermia. This way ?|- But what if Sarris survives ?
{32808}{32893}- I doubt it. I gave him both barrels.|- He has a very powerful ship.
{32895}{32985}If you got any more problems|with the guy, just give me a call.
{32987}{33045}- [ Bangs Step ]|- Ow !
{33090}{33153}- An interstellar vox.|- A what ? Hey.
{33155}{33248}- [ Beeping ]|- How can we thank you, Commander ?
{33250}{33381}You-- You have saved|our people.
{33456}{33593}Yeah. Okay. You know, you kids|have been great. You really have.
{33595}{33744}This thing is real lookin'.|Yoo-hoo. Hello ? [ Chuckles ]
{33781}{33867}Hey ! Where's my limo ?
{33909}{33967}Huh ?
{34177}{34249}[ Banging ]
{34251}{34311}[ Sloshing ]
{34313}{34387}[ Groans ]
{34521}{34609}[ Groans ]
{34611}{34714}[ Banging ]
{35177}{35265}§§ [ Female Voices Harmonizing ]
{35456}{35544}[ Screaming ]
{35742}{35830}[ Panting ]
{36135}{36252}[ Gwen ] Take it from us.|We've been all over the universe.
{36254}{36409}But we've never seen space-age values|like we've seen here at--
{36411}{36490}Tech Value|Electronic Superstore !
{36719}{36796}[ Monotone ]|By Grabthar's hammer,
{36885}{36957}what a savings.
{36959}{37023}All right !
{37025}{37117}Yeah. Let's hear it|for the N.S.E.A. Protector.
{37119}{37187}[ Chattering ]
{37244}{37314}- Brandon, are you okay ?|- Commander.
{37316}{37387}My apologies.
{37389}{37500}Evidently, we had a little|miscommunication regarding...
{37502}{37570}the voyage.
{37572}{37666}That you didn't show up.
{37668}{37738}[ Panting ]
{37740}{37840}- He did it again.|- [ Man Over P.A. ]|Thank you for coming out.
{37842}{37992}Do you know what time it is ? Why do|you even bother to show up at all ?
{37994}{38096}N-N-N-Not now.|Guys, I was there.
{38098}{38195}I was up there.|Remember yesterday at the convention ?
{38197}{38272}Those people dressed like aliens ?|They were aliens.
{38274}{38387}They were Termites or Dalmatians.|I can't really remember|'cause I was hungover.
{38389}{38450}But what they built|was extraordinary.
{38452}{38570}It was a huge spaceship.|I got to fight this guy named Sarris|and I kicked his ass.
{38680}{38806}I know what you're thinkin'.|But I can prove it. They gave me this.
{38855}{39008}No, no, no, no, no. But can you|talk to people in space on those ?
{39010}{39063}Protector,|this is the commander. Over.
{39065}{39155}- Oh, for God's sake.|- That's it. It's time to go !
{39157}{39235}This isn't mine.
{39237}{39323}- That kid. Where's that kid ?|- Begging your pardon, Commander ?
{39325}{39383}We come with news.|Sarris lives.
{39385}{39468}- He was able upon your departure|to make an escape.|- Listen. Tell them.
{39470}{39557}- However, he has contacted us|and wishes to negotiate a surrender.|- Sarris.
{39559}{39672}We humbly implore you to come|and negotiate the terms.
{39674}{39745}Huh ? They want me back ?|You want me back ?
{39747}{39869}Is this amazing ? They want me back, and|I want you guys to go with me. Please ?
{39871}{39948}Think about it.|Let's go. Yes !
{39950}{40017}You're-- You're goin' ?
{40019}{40086}Alexander, this is not--|I'm not kiddin' here.
{40088}{40156}This isn't some kind of prank.|I'm not kiddin'.
{40158}{40248}No, guys, guys, listen.|Come on. Gwen, Gwen, Gwen.
{40250}{40367}Stop. Come here. You know me, and|I'm a lot of things, but am I crazy ?
{40369}{40447}You know, it's one thing|to treat us this way.
{40449}{40533}It's another thing to do it|to your fans.
{40535}{40658}She's not a fan.|This is-- This is a Termite !
{40660}{40733}You should've just|let me hit him.
{40735}{40856}Boy, I didn't know|you could get that loaded.
{40858}{40957}I think we should've|just taken the gig.
{40959}{41033}I mean, who knows|the next time he'll ask us ?
{41035}{41132}Fred, he was drunk. Do you really think|he was talking about a job ?
{41353}{41418}- But you live with your mother.|- Did Jason come through here ?
{41420}{41506}Yeah, he's in there.|Hey, guys.
{41508}{41615}Ah. We are coming too.
{41617}{41732}- All of you wish to go to the ship ?|- Yes, we wish to go to the ship.
{41734}{41830}You see, we work together,|or not at all.
{41832}{41982}Wonderful. The commander|had me continue transmission|in case you changed your mind.
{41984}{42119}- Protector, requesting|four interstellar--|- Me too.
{42121}{42194}five pods|for immediate departure.
{42230}{42300}[ Hum Resonating ]
{42302}{42365}Guys.
{42367}{42439}- Guys.|- I look forward to meeting you all...
{42441}{42504}in person when you|arrive at the ship.
{42506}{42595}- End transmission.|- [ Whooshing ]
{42597}{42697}- [ Liquid Sloshing ]|- Oh, my God.
{42699}{42792}- [ Whooshing ]|- Anybody got any change ?
{42913}{42988}[ Exhales ]
{43332}{43420}[ Shrieking In The Distance ]
{43422}{43510}[ Shrieking Continues ]
{43828}{43894}[ Instruments Whirring ]
{44260}{44357}[ Whirring ]
{44710}{44798}[ Shrieking Continues ]
{44839}{44903}Our most sincere apologies.
{44905}{45043}- We forgot about|our appearance generators.|- You guys came.
{45045}{45105}Who wants the grand tour ?
{45107}{45205}[ Screaming ]
{45272}{45347}- [ Screaming Stops ]|- Anybody else ?
{45459}{45517}That was a hell of a thing.
{45647}{45726}- What's wrong with them ?|- I don't know. Come on.
{45740}{45820}That's right, guys.|Keep shaking it off. It gets better.
{45822}{45898}- Try some gum. It helps.|- Where are we ?
{45900}{46001}The twenty-third quadrant|of the gamma sector.|There's a map in the forward room.
{46003}{46048}I'll show you.|Come on.
{46050}{46146}- Welcome, my friends.|- This is Mathesar. He's their leader.
{46148}{46243}I am Mathesar.|On behalf of all my people,
{46245}{46342}I wish to thank you from|the deepest place in our hearts.
{46344}{46422}Mathesar,|this is, uh, my crew.
{46510}{46590}Dr. Lazarus.
{46592}{46658}[ Mathesar's Crew Whispering ]|Dr. Lazarus. Dr. Lazarus.
{46660}{46738}Lieutenant Madison.
{46740}{46818}[ Whispering ]|Lieutenant Madison.
{46984}{47072}Young Laredo,|how you've grown.
{47074}{47127}Young Laredo.
{47190}{47255}Tech Sergeant Chen.
{47257}{47340}[ Mathesar's Crew ]|Tech Sergeant Chen. Tech Sergeant Chen.
{47468}{47586}C-Crew man number--|Guy.
{47588}{47650}Guy.
{47652}{47752}You... know us ?
{47754}{47823}[ Chuckling ]
{47825}{47922}I don't believe there is a man, woman|or child on my planet who does not.
{47924}{48042}Since we first received transmission|of your historical documents,
{48045}{48162}we have studied every facet|of your missions and strategies.
{48164}{48278}- You've been watchin' the show ?|- Lieutenant, historical documents.
{48280}{48394}- H-Historical documents from out here ?|- [ Mathesar ] Yes.
{48396}{48492}The past hundred years our society|had fallen into disarray.
{48494}{48587}Our goals, our values had become|scattered. But since the transmission,
{48589}{48678}- we have modeled every aspect|of our society...|- [ Grunts ]
{48680}{48790}from your example,|and it has saved us.
{48792}{48931}Your courage and teamwork|and friendship through adversity--
{48933}{49025}In fact, all you see around you|has been taken from the lessons...
{49027}{49118}garnered from|the historical documents.
{49120}{49225}- Is this a-- a spaceship ?|- [ Jason ] No.
{49227}{49323}This is a star port|for the ship.
{49325}{49397}Would you guys|like to see the ship ?
{49445}{49503}[ Door Whooshing ]
{49871}{49950}[ Banging,|Air Rushing Outside ]
{50093}{50161}[ Alexander ]|Oh, my God !
{50323}{50389}It's real.
{50649}{50710}[ Mathesar ]|The generator room.
{50712}{50802}The beryllium sphere,|of course.
{50804}{50862}And as we continue--
{50864}{50931}The medical quarters|are to the left.
{50933}{51038}We went through some trouble|duplicating your cellular regeneration--
{51040}{51125}- Jason, what have you got us into ?|- What are we doing here ?
{51127}{51248}- Wow, the floors are so clean.|- We're just here to negotiate|this guy Sarris' surrender.
{51250}{51396}- It's no big deal.|- And the organ fabrication chamber|is coming along nicely.
{51398}{51458}It's no big deal ?
{51460}{51596}- Are you crazy ?|We have to get out of here.|- Oh, come on, guys.
{51598}{51666}Jason, we are actors,|not astronauts.
{51668}{51751}You guys wanna go home ?|Say the word, we'll go home.
{51753}{51818}Pay our bills,|feed our fish,
{51820}{51949}fall asleep in front of the TV|and miss out on all of this.
{51951}{52034}Come on. Do you guys|wanna do that ? Anybody ?
{52036}{52118}Gwen, come on.|Look at where we are. We're in space.
{52120}{52253}Alexander, this is the role|of a lifetime. You guys wanna leave ?
{52255}{52375}We have enjoyed preparing|many of your esoteric dishes.
{52377}{52488}Your Monte Cristo sandwich is a current|favorite among the adventurous.
{52490}{52548}The main barracks.
{52600}{52659}§§ [ Drums Play Cadence ]
{52962}{53021}At ease.
{53136}{53226}It's like throwing gasoline|on a flame.
{53331}{53389}What ?
{53391}{53487}I'm just jazzed about|being on the show, man.
{53685}{53754}[ Mathesar ]|lf you would all take your positions.
{53797}{53883}- [ Gwen ] Our what ?|- Guys.
{53953}{54048}- Oh. Oh.|- Oh.|- Oh, wh-- Hmm.
{54187}{54252}Look, this thingy.
{54295}{54383}I remember--|I remember I had it all worked out.
{54385}{54475}This is forward.|This is back.
{54477}{54537}[ Hum Resonating,|Whooshes ]
{54539}{54672}Commander, some of the crew|has requested to be present|at this historic event.
{54674}{54747}Sure. Bring 'em in.
{54749}{54823}[ Shrilling ]
{55197}{55330}[ Chuckles ] No pressure, huh ?|Glad I ain't the commander.
{55387}{55450}Laredo, take us out.
{55511}{55608}- Excuse me ?|- [ Chuckles ]
{55610}{55742}They designed those controls|after watching you.
{55744}{55855}- Take her out.|- [ Clears Throat ] Right, right.
{55857}{55920}Okay.
{55922}{56000}Right.
{56002}{56102}Right.|Take her out.
{56182}{56262}[ Banging ]
{56264}{56346}- [ Air Rushing ]|- [ Spaceship Revving ]
{56586}{56648}[ Beeping ]
{56783}{56885}[ Spaceship Rising ]
{57949}{58006}Okay.
{58008}{58066}Y-you gotta move|to the right.
{58068}{58162}- Hit parallel.|- Would you sit your ass down ?|Sit ! You wanna drive ?
{58257}{58387}[ Metal Scraping ]
{58389}{58490}- [ Nervous Chuckle ]|- [ High-Pitched Scraping ]
{58990}{59048}[ Scraping Stops ]
{59669}{59750}[ Jason ]|Oh. Mmm.
{59752}{59828}How are you enjoying|your steak, Commander ?
{59830}{59945}I'm really enjoying it.|This is like corn-fed lowa beef.
{59947}{60027}Yes. We programmed|the food synthesizer...
{60029}{60117}for each of you based on|the regional menu of your birthplace.
{60119}{60213}[ Jason ] I don't care where|you did it. It tastes great !
{60215}{60300}Are you enjoying your|Kep-mok bloodticks, Dr. Lazarus ?
{60302}{60371}Just like Mother|used to make.
{60516}{60594}So, um-- [ Groans ]|Tell me, Mathesar.
{60596}{60676}This Sarris person|that we're flying to meet,
{60678}{60749}- what does he want, exactly ?|- [ Gagging ]
{60751}{60860}He heard about the device--|the Omega 13.
{60862}{60947}Um, what is it ?|What does it do ?
{60949}{61019}We don't know.
{61021}{61103}We were hoping|you could enlighten us.
{61139}{61232}[ Nervous Chuckle ]
{61308}{61404}Oh.|The Omega 13 device.
{61406}{61501}We found that on an alien planet.|We don't know what it does either.
{61503}{61597}- [ Gasps ]|- Why don't you just turn it on|and see what it does ?
{61599}{61663}- [ Shrills ]|- [ Laughs ]
{61665}{61787}It has at its heart a reactor|capable of unthinkable energy.
{61789}{61863}If we were mistaken in our construction,|the device would...
{61865}{61954}act as a molecular explosive,|causing a chain reaction...
{61956}{62028}that would obliterate|all matter in the universe.
{62076}{62180}Has Sarris ever seen any|of the, uh, historical records ?
{62183}{62242}No, thank God, he has not.
{62244}{62392}Oh. So how does he know about|the Omega 13 device ?
{62520}{62651}Our former commander|was not... strong.
{62653}{62727}Former commander ?
{62763}{62864}I am sorry.|You deserve to be shown.
{62866}{62975}The tape was smuggled off|of Sarris' ship.
{62977}{63053}Originally, one of our own|tried to lead.
{63055}{63180}Is that all ?|After three days of this,
{63182}{63275}you still require...|incentive ?
{63277}{63360}- [ Shrieking ]|- [ Electrical Buzzing ]
{63362}{63432}[ Female ]|I have told you all I know.
{63434}{63514}If you have any mercy within you,|please, let me die.
{63516}{63630}[ Sarris ] When I grow weary|of the noises you make, you shall die.
{63632}{63704}[ Electrical Buzzing ]
{64056}{64152}Wait a minute, guys. Come on.|Hold on a minute. You just can't leave.
{64154}{64215}- Give me some time to think.|- He wants to think.
{64217}{64291}No, Jason, that's a wrap.|There's nothing to think about.
{64294}{64392}I'm not even supposed to be here. I'm|just crewman number six. I'm expendable.
{64394}{64512}I'm the guy in the episode who dies|to prove the situation is serious.|I gotta get out.
{64514}{64642}- Commander ?|- We gotta prepare the pods|for my crew's departure.
{64644}{64732}Begging your commander's pardon, sir.|We can't launch pods at the moment.
{64734}{64833}- Sarris will surely detonate|any objects leaving the ship.|- Sarris ?
{64835}{64950}Yes, sir. He's here now. Your presence|is required on the command deck.
{64952}{65020}[ Stammers ]
{65208}{65266}There's nobody here.
{65268}{65324}While my people are|talented scientists,
{65326}{65406}our attempt to operate|our own technologies...
{65408}{65475}under tactical simulation|have been disastrous.
{65477}{65596}- I have raised Sarris|on zeta frequency.|- [ Jason ] Mathesar--
{65599}{65680}We meet again, Commander.
{65682}{65780}Hello, Sarris. How you doin' ?
{65782}{65884}Better than my lieutenant.
{65886}{66034}He failed to activate the ship's|neutron armor as quickly as I'd hoped...
{66037}{66098}on our last encounter.
{66100}{66209}Yeah, well, you know,|I'd like to say I'm real sorry|about what happened before.
{66211}{66320}The whole thing was just--|just a misunderstanding.
{66322}{66385}Deliver the device to me,
{66387}{66484}or I will destroy your ship.
{66486}{66582}You know, um,|we'd like do that,
{66584}{66692}but frankly, Sarris, sir, we don't know|what it is or even where it is.
{66694}{66773}You have ten seconds !
{66775}{66856}I don't-- Ten seconds ?|I don't-- There--
{66858}{66982}You know-- Okay. Gosh darn it,|I give up. It's yours. You can have it.
{66984}{67078}You have to give me a minute|to put it in a box for you, okay ?
{67080}{67161}- Gwen. [ Clicks Tongue ]|- [ Groans ]
{67163}{67304}Don't panic. I've dealt with|this guy before. He's as stupid|as he is ugly. Come here.
{67306}{67403}- Jason.|- Not now, Gwen. Sit, sit, sit, sit.
{67405}{67479}We're gonna send everything|we can at him, all right ?
{67482}{67540}- [ Gwen ] Jason.|- Not now, Gwen !
{67542}{67627}Push these red buttons and send|everything we have towards him, okay ?
{67629}{67728}- Okay.|- All right, Gwen. [ Clears Throat ]
{67730}{67873}- Put me back on with him.|- Well, I'm trying to tell you,|you are back with him.
{67875}{68020}Perhaps I'm not as stupid|as I am ugly, Commander.
{68114}{68250}I gave you the...|"kill" gesture.
{68252}{68318}No, you gave me|the "we're dead" signal.
{68320}{68403}I was agreeing with you.|Like I know where the hold button is.
{68405}{68473}[ Guy ]|Hey, guys.
{68475}{68586}- [ Beeping On Monitor ]|- There's a red, uh, thingy...
{68588}{68649}movin' toward the green thingy.
{68651}{68758}- What ?|- Red thingy movin'|toward the green thingy.
{68806}{68893}I think-- I think|we're the green thingy.
{68895}{68997}A little present|for you, Commander.
{68999}{69066}We gotta get out of here. Move|this ship. Turn it. Move ! Let's go !
{69117}{69183}[ Gwen Screaming ]
{69239}{69317}[ Explosion ]
{69489}{69580}- [ Explosion ]|- [ Screams ]
{69582}{69668}- Tommy, let's go !|Get us out of here !|- Jason, what do I do ?
{69670}{69718}Go, go, go !
{69769}{69838}[ Screaming ]
{69870}{69929}Whoo !
{70075}{70198}They're turning.|They're coming !
{70322}{70424}Thrust ahead, full !
{70426}{70505}Fire at will.
{70577}{70651}- [ Explosion ]|- Go faster, Tommy !
{70654}{70780}- I'm going as fast as I can !|- She's still behind us !
{70782}{70870}Well, uh, uh, press turbo. I'm always|saying, "Press the turbo," right ?
{70872}{70956}- Oh, it's here. Right here.|- Press it and hold it down.
{70958}{71030}[ Explosion ]
{71032}{71091}- [ Whooshing ]|- Whoo !
{71140}{71213}[ Computerized Voice ]|The enemy is matching velocity.
{71215}{71317}- Enemy is matching velocity.|- We heard it the first time !
{71319}{71413}Gosh, I'm doing it.|I'm repeating the darn computer.
{71415}{71547}Hi, guys. Listen.|They're tellin' me...
{71549}{71682}the, uh-- the generators|won't take it.
{71684}{71768}The ship is breakin' apart|and all that.
{71770}{71836}Just F.Y.I.
{71838}{71956}- We've gotta stop !|- We stop and we die.|Tommy, just hold that down.
{71959}{72077}- You don't hold the turbo down.|It's for quick boosts !|- Oh, like you know.
{72080}{72196}[ Turbo Shutting Down,|Sputtering ]
{72198}{72286}- [ Alarm Blaring ]|- [ Gwen ] I remember that sound.
{72288}{72344}That's a bad sound.
{72346}{72471}Wait, wait, wait, wait. We might be able|to lose them in this cloud here.
{72473}{72549}Oh, I don't--|I don't think that's a cloud.
{72551}{72704}- Mathesar, what is this ?|- Tothian minefield left standing|from the Great War of 12185.
{72882}{72990}Oh, God ! [ Screams ]|Whoo !
{72992}{73051}[ Grunting, Screams ]
{73054}{73133}- [ Explosion ]|- [ Whimpering ]
{73273}{73420}Could you possibly try|not to hit every single one ?
{73422}{73530}Sorry, man. They're driftin'|towards us ! I think they're magnetic !
{73666}{73744}Continue forward, sir ?
{73791}{73849}Patience, Lieutenant.
{73880}{73938}Patience.
{74234}{74321}- We've gotta stop !|- We're almost through this.
{74387}{74476}[ High-Pitched Screaming ]
{74923}{74985}- You okay ? You all right ?|- Yeah.
{74987}{75093}- [ Groaning ]|- Everybody all right ? Where's Tommy ?
{75095}{75199}- [ Screaming ] Oh, man !|- Tommy ! You all right ?
{75202}{75317}No, my arm is broke--|No, don't touch it. Don't touch it.
{75319}{75414}- I'll take him to medical quarters.|- Thanks, Mathesar.
{75416}{75554}[ Screaming ]
{75614}{75688}Alex, where are you going ?
{75691}{75788}To see if there's a pub.
{76061}{76167}[ Computer ] Forward thruster shaft:|87 percent damage.
{76169}{76288}Aft vector guards:|96 percent damage.
{76291}{76427}Structural breaches|in quadrants 32, 34, 40--
{76429}{76538}- What about the engines ?|- Forward thruster shaft:
{76540}{76649}- 87 percent damage.|- Computer, what about the engines ?
{76651}{76808}- Why don't we have power ?|- The beryllium sphere|has fractured under stress.
{76810}{76933}- It's fractured.|- Can it be repaired ?
{76935}{77087}- Computer, can it be repaired ?|- Damage to beryllium sphere:|irreparable.
{77089}{77229}- New source of beryllium|must be secured.|- We need another one.
{77231}{77309}You broke the ship.|You broke the bloody ship.
{77311}{77369}Eh, ah--|[ Clears Throat ]
{77371}{77487}Computer, is there a replacement|beryllium sphere on board ?
{77489}{77621}Computer, is there a replacement|beryllium sphere on board ?
{77623}{77761}Negative. No reserve|beryllium sphere exists on board.
{77763}{77867}No, we have no extra|beryllium sphere on board.
{77870}{77946}You know, that is|really getting annoying.
{77948}{78041}Look, I have one job|on this lousy ship.
{78043}{78142}It's stupid,|but I'm gonna do it, okay ?
{78144}{78223}Sure, no problem.
{78399}{78498}A thousand apologies.|We have failed you.
{78500}{78572}[ Chuckles ]|How have you failed us ?
{78574}{78729}We have seen you victorious in|much more desperate situations.
{78731}{78845}The fault must lie with us,|with the ship.
{78847}{78955}No, Mathesar, it is not your fault,|and it's not the ship's fault.
{78957}{79016}It's-It's-It's-It's|my fault.
{79018}{79161}-We-We screwed--|-We are not the people you think we are.
{79163}{79227}I don't understand.
{79388}{79548}Didn't you make any TV shows|on your planet ? Any theater, films ?
{79550}{79617}The historical documents|of your culture.
{79619}{79752}Yes, in fact, we have begun to document|our history from your example.
{79755}{79899}No, not historical documents. They're|not all historical documents. I mean,
{79901}{80013}surely you don't think|that Gilligan's Island is a--
{80015}{80092}- [ All Moaning ]|- Those poor people.
{80131}{80202}[ Tommy ]|Oh, brother.
{80204}{80301}We're screwed.
{80333}{80430}Is there no one on your planet|who behaves in a way...
{80432}{80516}that's contrary|to reality ?
{80518}{80622}[ Gasping ]|You are speaking of--
{80625}{80683}- Deception, lies.|- Deception, lies.
{80685}{80848}We have only recently|become aware of this concept|in our dealings with Sarris.
{80851}{80953}Often, Sarris will say one thing|and do another.
{80955}{81036}Promise us mercy,|but deliver destruction.
{81038}{81141}It is a concept we are beginning|to learn at some great costs.
{81143}{81320}But if you are saying that|any of you could have traits|in common with Sarris--
{81322}{81407}- [ Laughing ]|- [ All Laughing ]
{81495}{81539}[ Laughing ]
{81604}{81753}Hey, Commander, listen. We found|some beryllium on a nearby planet.
{81756}{81830}We might be able to get there...
{81832}{81956}if we reconfigure|the solar matrix...
{81958}{82052}in parallel|for endothermic propulsion.
{82054}{82128}What do you think ?
{82226}{82301}- We'll do that !|- All right !
{82304}{82371}That's-That's-That's|right again.
{82373}{82450}That's-- C-C-Come on.|Group hug.
{82452}{82559}- Come on.|- [ All Murmuring ]
{82849}{82959}Dr. Lazarus, I hope|I am not breaching protocol,
{82961}{83084}but I am so very humbled|to stand in your presence.
{83086}{83160}I have studied your missions|extensively.
{83163}{83262}Though I am Thermian, I have lived|my life by your philosophy,
{83264}{83333}by the code|of the Mak'tar.
{83335}{83478}- Oh, good, that's very nice.|- By Grabthar's hammer, Dr. Lazarus.
{83480}{83589}- Don't do that. I'm not kidding.|- I'm sorry, sir, I was just--
{83591}{83650}Just don't.
{83686}{83744}Yes, sir.
{84026}{84108}Never give up,|never surrender.
{84290}{84351}Dr. Lazarus ?
{84353}{84471}Here is your surface mapper. I have|programmed it to the coordinates...
{84474}{84563}of a beryllium sphere|of sufficient density.
{84566}{84722}- Good luck on your mission, sir.|- Thanks.
{84965}{85044}You're doing good,|Tommy.
{85221}{85288}I changed my mind.|I wanna go back.
{85290}{85392}After the fuss you made|about getting left behind ?
{85394}{85454}Yeah, but that's when I thought|I was the crewman...
{85457}{85563}that stays on the ship, and something|is up there, and it kills me.
{85565}{85625}But now I'm thinking I'm the guy|who gets killed by some monster...
{85628}{85686}five minutes after we land|on the planet.
{85688}{85746}You're not gonna die|on the planet, Guy.
{85748}{85827}I'm not ?|Then what's my last name ?
{85829}{85927}It's, uh, uh--|I don't know.
{85929}{86010}Nobody knows !|Do you know why ?
{86012}{86097}Because my character isn't|important enough for a last name,
{86099}{86197}because I'm gonna die|five minutes in.
{86199}{86263}Guy, you have a last name.
{86265}{86359}- Do I ? Do I ?|- Yes !
{86361}{86463}For all you know,|I'm just crewman number six.
{86515}{86617}Mommy ! Mommy ! Mommy !
{86619}{86669}Are we there yet ?
{86671}{86744}- Mommy !|- [ Jason ] Tommy !
{86746}{86849}- Look out ! Oh, no !|- [ Alexander ] Pull out !
{86851}{86912}[ Fred Moaning ]|Oh, yeah !
{86914}{86988}[ Moaning Continues ]
{87435}{87542}- [ Beeping ]|- [ Guy ] Don't open that !|It's an alien planet !
{87544}{87643}Is there air ?|You don't know !
{87694}{87868}[ Sniffing, Breathing ]|Seems okay.
{88334}{88393}Here we go.
{88526}{88584}[ Jason ]|Which way, Alexander ?
{88663}{88721}[ Beeping ]
{88768}{88826}This way !
{88878}{88936}Wait. No.
{89061}{89139}- That way.|- You were holding it upside down.
{89141}{89208}- Shut up.|- You know, with|all that makeup and stuff,
{89210}{89268}I actually thought|you were smart for a second.
{89270}{89335}You think you could|do better, Laredo ?
{89337}{89426}- All right with that Laredo stuff.|- [ Guy ] Oh, we're so screwed.
{89428}{89536}Come on, come on, come on,|if we wanna finish this mission,|we have to use self-control.
{89538}{89621}[ Gwen ] "Self-control" ?|That's funny, coming from a guy...
{89623}{89738}who slept with every Turekian slave|girl and moon princess on the show.
{89740}{89814}[ Jason ] Ever occur to you,|had you been more supportive,|you might've been--
{89881}{90017}[ Alexander ] Wow. Must be|some sort of mining facility.
{90019}{90146}- Where are the miners ?|- Something bad happened here.
{90148}{90247}- Will you relax ?|- [ Beeping ]
{90298}{90456}There they are.|Beryllium spheres. Let's go.
{91051}{91143}- [ Gasping ]|- [ Chattering ]
{91223}{91286}Look at that.
{91288}{91444}Would you look at that ?|They look like little children.
{91505}{91578}Could they be the miners ?
{91580}{91667}Sure, they're like|three years old.
{91757}{91823}Miners, not minors.
{91825}{91897}- You lost me.|- I don't like this.
{91899}{91998}- I don't like this at all.|- They are so cute.
{92000}{92123}Sure, they're cute now.|In a second, they're gonna get mean.
{92125}{92234}They're gonna get ugly somehow, then|there's gonna be a million more of them.
{92236}{92356}[ Gasping ] Look.|There's a little hurt one.
{92359}{92443}[ Whimpering ]
{92445}{92490}Oh.
{92493}{92597}[ Whimpering Continues ]
{92600}{92669}Hi.|Hi there.
{92671}{92764}- Ah !|- Shh !
{92766}{92885}- Did you guys ever watch the show ?|- [ Chattering ]
{92888}{92954}See ?
{92956}{93018}They're gonna help|the little hurt one.
{93090}{93171}[ Whispering ]
{93173}{93242}[ Snarling ]
{93296}{93392}I'm so sick|of being right.
{93394}{93471}- Let's get out of here before|one of those things kills Guy.|- Wait a minute.
{93473}{93554}We're not going anywhere without|a beryllium sphere. We need a plan.
{93556}{93636}Fred, I need a diversion|to clear the compound of those things.
{93638}{93713}Then, Alex and Gwen and I|will go get a sphere.
{93716}{93806}Tommy, get up on that ridge,|and if you see them come back,|give me a signal, all right ?
{93809}{93863}Why does this sound|so familiar ?
{93865}{93946}"Assault on Voltareck 3,"|episode 81.
{93948}{94057}- We're doing episode 81 ?|- Whatever. The one with|the hologram, the wall of fire.
{94059}{94151}Well, how the hell is Fred|supposed to project a hologram ?
{94153}{94241}- What did we do in episode 81 ?|- It's just a rough plan.
{94243}{94374}- What difference does it make|if it's episode 81 or not ?|- 'Cause I died in episode 81 !
{94376}{94477}- Shh ! Episode 51, right ?|- This is ludicrous.
{94479}{94537}Why are you listening to this fellow ?|May I remind you:
{94539}{94618}He's wearing a costume,|not a uniform.
{94620}{94738}He's no more equipped to lead us|than this fellow. No offense.
{94778}{94853}Look, they're gone.
{94856}{94911}- Where'd they go, back inside ?|- I don't know.
{94913}{94998}- Nobody was watching.|- All right, all right !
{95000}{95089}Listen up. Here's the plan.|Gwen, Fred, Alex and l,|we'll go down and get a sphere.
{95091}{95153}Fleegman, you set up a perimeter,|and Tommy, you're lookout.
{95155}{95258}- You see anything at all,|you give us a signal.|- What kind of a signal ?
{95261}{95404}- Any kind of signal.|- Okay, I'll do my hands|like this, and caw, caw !
{95406}{95484}What are you, an infant ?|Look, we have these.
{95569}{95677}- That-- Sorry.|- All right, let's go.
{95679}{95737}[ Grunting ]
{95886}{95995}- Does rolling help ?|- Uh-huh, it helps.
{95997}{96103}- Where's your gun ?|- It helps.|- Shoot !
{96334}{96392}- Oh.|- What ?
{96435}{96508}[ Jason Chuckling ]|Never give up, never surrender.
{96510}{96568}[ Together ]|Oh, shut up.
{96570}{96707}Caw, caw, I said !|[ Yelling ]
{96709}{96813}[ Screaming ]|Run ! Run ! Run !
{96816}{96946}- They're everywhere,|they're everywhere.|- Everywhere !
{96948}{97027}- Come on, let's go.|- Let's go !
{97029}{97137}- [ Yelling ]|- [ Jason ] Hurry !
{97139}{97253}They're everywhere.|Come on !
{97255}{97342}[ Jason ]|Don't look back. Don't look back.
{97344}{97412}- We're not gonna make it.|- [ Snarling ]
{97414}{97488}- [ Screams ]|- Oh, God !
{97491}{97622}- [ Guy ] I knew it, I knew it.|I knew this was gonna kill me.|- Hurry ! Go, go, go !
{97624}{97713}[ Jason ]|Come on. Push. Let's go. Go !
{97715}{97779}I got it, but it's gonna|take a few seconds.
{97781}{97833}I got it, I got it !
{97835}{97914}- Go ahead.|- There's no time. Get in, get in.
{97916}{97996}Of course, I forgot, you've got|to be the hero. Haven't you ?
{97998}{98088}Heaven forbid anybody else gets|the spotlight ! Oh, no, Jason Nesmith--
{98091}{98197}- Oh ! Jason ! Jason, come on !|- [ Screeching ]
{98199}{98306}- Hurry !|- Tommy, go ! Go ! I mean it !
{98308}{98447}Help ! No, no, no ! Jason, please !|Tommy, stop the pod, stop it !
{98449}{98567}- I can't stop it. It's on autopilot.|- Go ! Leave him !
{98569}{98627}[ Gwen ]|No !
{98773}{98831}[ Screeching ]
{98899}{98957}Oh, right !
{98959}{99047}Of course, it's always|about you, isn't it ?
{99139}{99200}[ Panting ]
{99203}{99261}[ Chattering ]
{99404}{99477}[ Screeching ]
{99808}{99866}[ Groaning ]
{99908}{100023}[ Screaming ] Oh, hey !|[ Grunting ]
{100025}{100094}- [ Growling ]|- [ Groaning ]
{100096}{100155}[ Chanting ]|Gorignack, Gorignack.
{100158}{100276}- [ Groaning Continues ]|- Gorignak, Gorignak,|Gorignak, Gorignak.
{100319}{100420}Jason ? Jason,|can you hear me ?
{100422}{100526}- Yeah, Gwen, you got me.|- Thank God. Are you okay ?
{100529}{100653}Yeah. As a matter of fact,|I've got Gorignak staring me|in the face right now.
{100655}{100760}But you know what ?|I think I can take him.
{100763}{100821}[ All Groaning ]
{100823}{100904}Jason, we're gonna use the digital|conveyor to get you out of there.
{100906}{100976}- The digital conveyor ?|- Yeah.
{100978}{101102}You gonna have me diced into cubes|and sent up there in a million pieces ?
{101104}{101187}- Right.|- Well, you know what ?
{101189}{101278}I think I'll take my chances|with Gorignak.
{101280}{101419}We're getting you out right now.|It's perfectly safe, isn't it, Teb ?
{101421}{101499}It has never been|successfully tested.
{101501}{101598}- What did he say ?|- Hold, please.
{101600}{101674}Theoretically, the mechanism|is fully operational.
{101676}{101784}However, it was built to accommodate|your anatomy, not ours.
{101786}{101870}But now that Tech Sergeant Chen|is here, he can operate it.
{101872}{101985}It was designed watching his motions|from the historical documents.
{101987}{102070}I-l-l mean, I can't.|[ Stammering ]
{102072}{102144}- I-l can supervise.|- Jason, we're gonna test it.
{102146}{102242}- On what ?|- How about that pig lizard ?
{102244}{102377}- Hey, I'm doing all right|with the pig lizard.|- Please, Fred. And hurry.
{102380}{102470}[ High-Pitched Squeal ]
{102473}{102576}I'm sorry. It's very exciting|to watch the master at the controls.
{102578}{102676}The operation of the conveyor is|much more-- hmm-mmm-- art than science.
{102678}{102768}Stand back, Jason.
{102830}{102910}Gorignak, Gorignak,|Gorignak.
{102912}{102992}[ Growling ]
{103294}{103368}[ All Screaming, Groaning ]
{103495}{103585}- What ? What was that ?|- Uh--|- Nothing.
{103588}{103679}- I heard some squealing or something.|- Oh, no, everything's fine.
{103682}{103738}But the animal is|inside out.
{103740}{103833}I heard that.|It turned inside out ?
{103835}{103936}[ Screaming ]
{103938}{103997}And it exploded.
{104000}{104128}Did I just hear that the animal|turned inside out and exploded ?
{104130}{104188}Hello ?
{104253}{104312}Hold, please.
{104314}{104372}Hey, wait a minute.|Guys, guys.
{104374}{104459}If the pig lizard is gone,|why are they still yelling "Gorignak."
{104461}{104568}Teb, hit|the translation circuit.
{104570}{104660}[ Chanting Continues ]|Gorignak, Gorignak. Rock.
{104663}{104762}Rock, rock, rock.
{104764}{104858}- [ Chattering ]|- Jason,
{104860}{104953}I don't think the pig lizard|was Gorignak.
{104955}{105028}What the hell|you talkin' about ?
{105313}{105371}Oh, darn.
{105373}{105431}[ Sighs ]
{105704}{105759}Digitize me !
{105761}{105819}- Come on, Fred.|- Come on, guys, digitize me !
{105821}{105911}- Not me.|- Come on, they based it|on your hand movements.
{105914}{105972}- Am I the only one who saw|that thing inside out ?|- No, no, no, no.
{105974}{106032}I-I-I'm not the guy.
{106034}{106127}I'm not Tech Sergeant Chen.|Kwan's not even my real name.
{106129}{106190}Fred's no good, Jason.|You're just gonna have to kill it.
{106193}{106311}Kill it ? Well,|I'm open to any suggestions.
{106313}{106378}Go for the eyes,|like in episode 22 !
{106380}{106473}It doesn't have|any eyes, Tommy.
{106475}{106534}Go for the mouth or throat,|its vulnerable spots !
{106536}{106626}It's a rock.|It doesn't have any vulnerable spots !
{106629}{106726}I know ! You construct a weapon.|Look around you.
{106728}{106831}- Can you form some sort|of rudimentary lathe ?|- A lathe !
{106834}{106942}Get off the line, Guy ! Alexander,|you're my advisor. Advise me.
{106944}{107032}Well, you're just gonna have to|figure out what it wants.
{107034}{107092}What is its motivation ?
{107094}{107202}It's a rock monster.|It doesn't have motivation.
{107204}{107278}See, that's your problem, Jason.|You were never serious about the craft.
{107339}{107401}[ Screaming ]|Oh ! Fred, can you hear me ?
{107403}{107478}Fred, are you there ?|[ Screaming ]
{107481}{107568}- Kinda.|- You can do it, Fred. It's up to you.
{107570}{107660}Oh, no, no, no. Jason,|I'll just-- I'll just mess it up.
{107663}{107733}You did it for four years|on the show. Do it now.
{107735}{107817}That was the show.|I'm not that guy.
{107819}{107903}You never forgot a line.|You never missed a mark.
{107905}{107948}[ Grunting ]
{107950}{108003}That's not me anymore, man.
{108069}{108167}It is you, Fred.|You just stopped trying.
{108233}{108319}You could do this, Fred. I know|in my heart, you're gonna save my life.
{108321}{108407}- I am ?|- No doubt about it, Fred.
{108409}{108477}Fred !
{108521}{108581}Fred, can you hear me ?
{108617}{108682}Fred !
{108684}{108802}Fred ?|I don't wanna die down here.
{108805}{108906}Digitize me, Fred !
{108981}{109055}- Oh, wow.|- Oh !
{109058}{109107}- Tech Sergeant Chen.|- Yeah !
{109236}{109338}Oh !
{109340}{109413}I see you managed|to get your shirt off.
{109543}{109617}- I did it.|- Welcome back, Fred.
{109619}{109728}All right, did we get|the beryllium sphere installed ?
{109730}{109846}- Yes, we are back to full power.|- Great. Engines and pods ?
{109848}{109945}- Fully operational.|- Perfect ! We'll crank this sucker up.
{109947}{110049}You can drop us off, and you guys can be|back to your home planet before supper.
{110051}{110121}Oh, no, sir,|we have no reason to go back.
{110123}{110194}Sure you do.|Family, friends. Come on.
{110196}{110272}We are all that is left.
{110453}{110567}- I didn't know that.|- Sir, I have raised the command deck.
{110686}{110789}Mathesar, meet us up|on the command deck.
{110792}{110869}Mathesar.
{110871}{110967}Mathesar, Quellek !
{110969}{111069}Why can't we reach them ?
{111331}{111446}- [ Growling ]|- [ Guy Groaning ]
{111532}{111606}[ Groaning ]
{111651}{111784}[ Mumbling ]|Thank God, you're alive.
{111786}{111922}Now you will face justice,|Sarris.
{111925}{112081}At every turn, you demonstrate|the necessity for your extermination.
{112083}{112149}Leave him alone.
{112206}{112284}You wish to save the life|of this man ?
{112286}{112351}Yeah. Yes.
{112438}{112520}Then tell me--|what does it do,
{112522}{112652}- this Omega 13 ?|- I don't know what it does.
{112766}{112837}I said, I don't know.
{112891}{112976}- Is it a bomb ?|- I don't know.
{112978}{113067}- A booby trap ?|- I don't know !
{113069}{113149}- Tell me !|- I don't know !
{113151}{113236}- [ Moaning ]|- Do you think I'm a fool ?
{113238}{113375}That the commander does not know|every bolt, every weld in his ship ?
{113448}{113539}Prepare a tear harness...
{113542}{113600}for the female.
{113602}{113700}- [ Grunting ] No ! Gwen, no !|- [ Screams ]
{113702}{113800}- [ Groaning ]|- You brute ! Let go of me !
{113802}{113867}[ Groaning ]|I'm not the commander.
{113869}{113936}What did you say ?
{113938}{114035}I said,|I'm not the commander.
{114037}{114126}Leave them alone.|There's no reason to hurt them.
{114129}{114204}- They don't know anything.|- Explain.
{114207}{114380}Gwen, show him|the historical documents.
{114382}{114454}[ Sighing ]|Computer,
{114456}{114585}show the historical documents|of the Galaxy Quest missions.
{114587}{114719}§§ [ Galaxy Quest Theme Music ]
{115108}{115195}[ Chuckling ]
{115197}{115274}[ Laughing ]
{115366}{115424}Wonderful.
{115511}{115674}You have all done far greater damage|than I ever could have.
{115676}{115740}Bravo !
{115742}{115822}[ Chuckles ]|Bravo.
{115824}{115901}This is a moment|I will treasure.
{115903}{115972}Explain to him...
{115974}{116097}who you all really are.
{116099}{116171}Tell him !
{116244}{116303}Explain !
{116408}{116469}Mathesar, the--
{116472}{116566}There's no such person|as Captain Taggart.
{116568}{116721}My name is Jason Nesmith.|I am an actor.
{116757}{116825}We're all actors.
{116827}{116936}He doesn't understand.
{116938}{117064}Explain as you would|a child.
{117158}{117271}We, uh--|We pretended.
{117414}{117479}We lied.
{117481}{117641}- [ Moaning ]|- Yes ! You understand that,|don't you, Mathesar ?
{117643}{117766}Mathesar, l--|I'm not a commander.
{117768}{117875}There's no National Space|Exploration Administration.
{117877}{117966}We don't have a ship.
{117968}{118067}But there it is.
{118136}{118194}That ship is that big.
{118196}{118296}But inside,|I see many rooms.
{118298}{118412}You've seen plywood sets|that look like the inside.
{118414}{118577}Our beryllium sphere is-is wire|with plaster around it.
{118579}{118666}And our--|[ Chuckles ]
{118668}{118755}our digital conveyor is...
{118757}{118842}Christmas tree lights.
{118844}{118917}It's a decoration.|It's all fake.
{118990}{119049}Just like me.
{119133}{119239}But why ?
{119296}{119354}It's difficult|to explain.
{119406}{119464}On our planet, we--
{119541}{119704}we pretend|to-to entertain and--
{119707}{119810}Mathesar,|I am so sorry.
{119813}{119896}God, I am so sorry.
{119898}{120016}- [ Gagging ]|- So now you know.
{120019}{120181}Lieutenant Lathe, hardwire|the reactor core to overload.
{120183}{120306}I would like to blow|this troublesome vehicle to dust.
{120308}{120392}- Sarris, what about my people ?|- Yes !
{120394}{120496}Far too simple|a death for them, isn't it ?
{120498}{120628}Lathe, open an oxygen seal|on level "C."
{120630}{120760}Let the air in a bit|for our friends.
{120762}{120857}Son of a--|[ Groaning ]
{120939}{121024}Release them...
{121026}{121084}into space.
{121163}{121294}[ Automated Voice ] Core overload.|Emergency shutdown: overridden.
{121296}{121420}Core implosion estimated|in nine minutes.
{121422}{121589}- Core overload.|Emergency shutdown: overridden.|- Hey !
{121591}{121699}[ Alexander ]|Where's the happy ending, Jason ?
{121746}{121838}Never give up,|never surrender.
{122014}{122169}Maybe it's about time you just backed|off, you fin-headed monstrosity.
{122171}{122261}- [ Gwen ] Jason ?|- You what ?
{122264}{122394}You're starting to act|like you did in episode 17,
{122396}{122460}you scene-stealing hack.
{122534}{122617}Oh, right.
{122619}{122714}Well, how does it feel, Jason ?
{122716}{122802}-Was it worth it ? You murdered us all !|-Shut up.
{122804}{122876}Hundreds to die|just because of you.
{122878}{122949}- I told you to shut up.|- Both of you, get in there.
{122951}{123040}Hundreds to die just because|you wanna play a big commander.
{123042}{123131}- You raving lunatic.|- Then I'll see you in hell, won't I ?
{123538}{123710}- [ Alexander ] Look out, Jason !|- Get his gun ! Get the gun !
{123712}{123782}[ Guy ]|Take that !
{124062}{124120}[ Screaming ]
{124207}{124288}Sorry, I was-- Door was|a little sticky. Did you see that ?
{124290}{124379}I'll get one of my boys up here|with a can of WD-40.
{124501}{124598}- You used to pull your punches.|- Scene-stealing hack, thank you.
{124600}{124670}- Raving egomaniac.|- Can't think where I got that from.
{124672}{124731}Guys.
{124734}{124792}Look.
{124890}{124961}They're suffocating.
{125107}{125245}Core overload.|Emergency shutdown: overridden.
{125247}{125356}Core implosion estimated|in eight minutes.
{125398}{125526}General, your transport|is ready for departure !
{125671}{125802}Core overload.|Emergency shutdown: overridden.
{125804}{125907}Core implosion estimated|in seven minutes.
{125961}{126062}- Computer, shut down the core.|- Unable.
{126064}{126216}Memory checks invalid.|Core system's hardware damaged.
{126218}{126297}All right, listen up, this is what|we gotta do. Gwen, you and l,
{126299}{126371}we're gonna get to the core|and shut it down manually.
{126373}{126431}Fred, take Guy and Laliari.|You find that valve.
{126433}{126486}Shut it off before|those Thermians run out of air.
{126488}{126589}Alexander, get to the barracks. Wedge|a door open, in case they can't do that.
{126591}{126656}- Okay.|- Wait, Jason. What about me ?|What do I do ?
{126658}{126789}You're gonna practice driving.|Let's go !
{126791}{126849}Practice driving.
{126862}{126950}- So we get to shut down|a neutron reactor.|- That's right.
{126952}{127010}I hate to break it|to you, Jason,
{127012}{127094}but I don't know how to|shut down a neutron reactor,
{127096}{127164}and unless you took a learning annex|course I don't know about,
{127166}{127252}I'm pretty sure you don't know how|to shut down a neutron reactor either.
{127254}{127351}No, I don't,|but I know someone who does.
{127438}{127530}- [ Knocking ]|- Brandon, honey, garbage.
{127533}{127605}Aw, Mother,|I'm quite busy.
{127607}{127679}Come on, Brandon,|don't make me ask you again.
{127681}{127804}[ Sighing ] Just ten more minutes.|Okay, Ma, I promise.
{127841}{127899}[ Sighing ]|Great.
{128000}{128069}[ Beep ]
{128180}{128300}- [ Beep ]|- Hello ? Anybody there ?
{128348}{128417}Hello ?
{128419}{128477}Hello ?
{128479}{128597}Got him. Listen to me.|This is Jason Nesmith.
{128599}{128727}I play Commander Peter Quincy Taggart,|N.S.E.A. Protector.
{128729}{128846}We accidentally traded boxes the other|day when we bumped into each other.
{128848}{128988}Oh ? Oh.|Commander, I see.
{128990}{129078}- Okay.|- What's your name, son ?
{129080}{129157}[ Sighs ]|Brandon.
{129159}{129243}Brandon, I remember you|from the convention, right ?
{129245}{129354}You asked all those little|technical questions about the ship,
{129356}{129415}and I was a little short|with you.
{129418}{129535}Yes, yes, I know, Commander,|and I actually wanna--
{129537}{129639}I just wanted to tell you that|l-l thought a lot about what you said.
{129641}{129724}- It's okay. Listen.|- But I want you to know...
{129726}{129830}that I'm not a complete|brain case, okay ?
{129833}{129921}I understand completely|that it's just a TV show.
{129923}{129989}- H-Hold-- Wait a minute.|- [ Brandon Continues ]
{129991}{130109}Stop for a second.|Stop. Wait. It's all real.
{130111}{130229}Oh, my God, I knew it.|I knew it ! I knew it !
{130232}{130335}The crew and I are in a lot of trouble,|and we need your help.
{130371}{130501}Core overload.|Emergency shutdown: overridden.
{130503}{130601}Core implosion estimated|in six minutes.
{130603}{130700}- [ Gasping ]|- [ Screaming ]
{130702}{130779}Sir, it's you.|Thank Ipthar.
{130830}{130919}Quellek ?|What are you doing up there ?
{130996}{131112}I avoided capture by using|your Mak'tar stealth face.
{131114}{131202}- Where is everyone ?|- Come with me.
{131204}{131277}I'll explain on the way.
{131358}{131426}All right, we're at level "C,"|hallway five. Now what ?
{131428}{131571}Um, go to weapons storage,|your second left, through the passage.
{131573}{131666}And that leads to a system|of utility corridors|through the bowels of the ship.
{131668}{131751}- Open.|- You know, I'm gonna get Kyle.
{131753}{131837}He knows the utility tunnel system|better than anybody alive.
{131902}{131960}...38, 39, 40.
{132034}{132130}All we have to do is|turn off the valve to the barracks.
{132307}{132383}- Hi, Brandon.|- No time for pleasantries, Kyle.
{132386}{132504}We have a level five emergency.|You still got the utility systems|walk-through, right ?
{132507}{132616}Yeah, I've got sectors|one through twenty-eight.|Hollister has the upper levels.
{132618}{132677}Great.|We'll get everybody on-line.
{132915}{133074}- Pedal to the metal, Commander.|- Pedal to the metal, Commander.
{133122}{133192}General !|I have just received word...
{133194}{133274}that the commander of the Protector|and his command crew...
{133276}{133341}have escaped custody.
{133343}{133401}What ?
{133471}{133628}- Find them !|- But sir ! My men--|The core implosion--
{133630}{133699}Find them !
{133749}{133846}All right, Brandon, I see five ducts|in this room. Which way do we go ?
{133848}{133909}Enter the passage|second to your left...
{133912}{134004}and just continue straight|for 50 meters.
{134007}{134104}Ducts ?|Why is it always ducts ?
{134106}{134166}- Ah, there will be a slight drop.|- [ Screaming ]
{134391}{134500}Thanks for the heads-up,|Brandon ! You okay ?
{134651}{134731}They're dying.
{134733}{134809}- Wait a minute.|We gotta go across this thing ?|- Yes.
{134812}{134930}- Don't look down.|- What I'd give to see|what you're seeing.
{134932}{135050}- What are you talking about ?|- You're deep in the underbelly|of the Omega 13 !
{135052}{135140}Oh, it must be spectacular.
{135142}{135226}It-It doesn't look|like much to me.
{135228}{135402}There's just these few walls|and this dumb spinning fan|that we have in every single--
{135789}{135917}Brandon, what does|the Omega 13 device do ?
{135919}{136016}Uh, many have believed|that it is a matter collapser.
{136018}{136145}A bomb capable of destroying pretty much|everything in about 13 seconds.
{136147}{136247}- But myself and others are convinced|that what it is...|- I'm gonna go. Go.
{136249}{136319}is a matter rearranger,
{136321}{136402}affecting a 13-second time jump|to the past.
{136404}{136547}Why 13 seconds ?|That's really not enough time|to do anything of any importance.
{136549}{136661}- It'd be time to redeem|a single mistake.|- What ?
{136663}{136799}- [ Lasers Blasting ]|- Go, go, go, go !
{136807}{136899}We-We gotta turn off that valve.|Their oxygen's almost gone.
{136936}{136995}Listen.|I'll go in.
{136998}{137077}I'll create a distraction.|I've got this. I'm okay.
{137079}{137165}I'm gonna be able to hold him back|long enough for the aliens to escape.
{137167}{137271}- That's suicide.|- I'm just a glorified extra, Fred.
{137274}{137389}I'm a dead man anyway. If I'm gonna die,|I'd rather go out a hero than a coward.
{137391}{137515}Guy, Guy, maybe you're|the plucky comic relief.
{137517}{137575}You ever think|about that ?
{137612}{137670}- Plucky ?|- Oh, besides,
{137672}{137776}I just had this|really interesting idea.
{137779}{137839}Are you stoned ?
{137842}{137935}Gotta get her up|and give them some time.
{137938}{138025}- [ Grunting ]|- Sir, perhaps together--
{138027}{138126}the Mak'tar chant of strength:|Larak tarath.
{138128}{138220}- Larak tarath, larak tarath.|- Larak tarath.
{138223}{138352}[ Together ] Larak tarath, larak tarath,|larak tarath, larack tarath.
{138608}{138684}All right, Brandon, we're across.|Now what ?
{138687}{138808}You wanna take a left and then just|straight on through the chompers.
{138811}{138864}"The chompers" ?
{139024}{139124}- Well, screw that.|- How are we supposed|to get through this ?
{139126}{139190}Hollister, do you have|the sequence yet ?
{139192}{139260}Okay, the sequence is...
{139262}{139345}two-two-four-two--
{139347}{139439}What is this thing ?|I mean, it serves no useful purpose...
{139442}{139545}for there to be a bunch|of chompy, crushy things|in the middle of a hallway !
{139548}{139666}We shouldn't have to do this.|It makes no sense ! Why is it here ?
{139668}{139750}- 'Cause it's on the television show.|- Well, forget it !
{139752}{139855}I am not doing it !|This episode was badly written !
{139858}{139925}Okay, Commander, now, as soon|as the first crusher hits you--
{139927}{139985}- [ Screaming ]|- It just did !
{139987}{140055}- Okay, go now.|- Go !|- [ Screaming ]
{140057}{140146}Go ! Stop !
{140149}{140238}Go !|Wait a minute.
{140241}{140324}Come on,|come on, come on.
{140366}{140450}Go ! Go !
{140452}{140511}Go ! Go !
{140513}{140601}- Go !|- Stop, stop. Go !
{140603}{140661}- Stop !|- [ Screaming ]
{140663}{140734}Jump, Commander, jump !
{140736}{140847}Whoever wrote this episode|should die !
{140900}{140958}This should be interesting.
{140992}{141050}[ Beeping ]
{141109}{141167}[ Chattering ]
{141412}{141456}[ Chattering Stops ]
{141501}{141567}[ Screaming ]
{141569}{141644}It's the simple things in life|you treasure.
{141693}{141751}That's great.
{141856}{141921}Now, we better get--
{142054}{142112}Get a room, guys.
{142173}{142240}Whoa !
{142338}{142397}Hey, Fred.
{142459}{142535}Hey, Fred, uh--
{142608}{142729}Oh, that's not right.|Oh !
{143562}{143667}Sir, the pressure--|it's normalizing.
{143718}{143776}All right !
{143823}{143908}We are saved.
{143910}{143969}He has saved us.
{143971}{144083}Commander Taggart|has saved us !
{144085}{144143}[ All Cheering ]
{144235}{144294}It's just not fair.
{144359}{144471}All right, Quellek,|let's get back to the commander.
{144473}{144540}[ Laser Blast ]
{144542}{144639}I'm-I'm shot.
{144839}{144904}[ Groaning ]
{145116}{145223}- Quellek ?|- [ Panting ]
{145354}{145412}That's not too bad.
{145414}{145514}We'll get you to the medical quarters,|and you'll be fine.
{145516}{145606}It has been my greatest honor|to serve with you.
{145609}{145725}I have been blessed, sir.|I-l--
{145727}{145790}Don't speak, Quellek.
{145930}{145996}You'll forgive|my impertinence, sir,
{145998}{146070}but even though|we had never before met,
{146072}{146190}I always considered you|as a father to me.
{146267}{146356}Quellek.
{146388}{146470}By Grabthar's hammer,
{146472}{146571}by the sons of Warvan,
{146573}{146732}you shall be avenged.
{147786}{147846}[ Screaming ]
{147849}{147961}...13, 14, 15, 16,|17, 18, 19 !
{147963}{148071}- All right, Brandon,|how do we shut this thing down ?|- Okay, just push the blue button.
{148074}{148149}- The blue button-- is that it ?|- Yeah, why ? What's wrong ?
{148152}{148241}Nothing. I just thought it'd be|more complicated than that.
{148292}{148410}Core implosion estimated|in 20 seconds.
{148697}{148790}Brandon, it's not working.|Brandon !
{148873}{148933}Mother, I cannot stress enough|the severity...
{148936}{149040}- of the commander's predicament.|- Don't forget the recyclables !
{149043}{149161}Core implosion estimated|in ten seconds.
{149201}{149259}- Nine, eight,|- Gwen, l--
{149261}{149319}- seven, six,|- I've always--
{149321}{149406}- five, four,|- Jason, oh, Jason.
{149408}{149495}three, two, one.
{149794}{149890}- It always stops at one on the show.|- [ Laughing ]
{149892}{149958}Um, what were you saying ?
{149962}{150018}- Sir !|- What ?
{150020}{150087}The core detonation sequence|on the Protector has been aborted.
{150089}{150156}Impossible !|Impossible !
{150158}{150295}Lock a complement of implosion missiles|under the Protector.
{150298}{150409}Tear her apart.
{150411}{150469}[ Lasers Blasting ]
{150698}{150833}He's finished. Alexander,|listen to me. It's okay, it's okay.
{150836}{150907}The Thermians can handle it from here.|We gotta go. Come on.
{150909}{150967}[ Screaming ]
{150969}{151047}We need that armor|back up !
{151049}{151189}- Get me a forward view right now !|- Plasma armor: engaged.
{151191}{151296}- [ Rumbling ]|- All right, Tommy, see if you can|lose 'em in that mine field.
{151299}{151381}- M-Mine field ?|- Pedal to the medal, right now !
{151383}{151446}- Pedal to the medal !|- All right, let's go !
{151743}{151819}Good going, Tommy.|Great going.
{151822}{151894}Thrust ahead-- full !
{151896}{152006}Into the field !|Go !
{152152}{152299}- Tommy, can you get us closer|to these mines ?|- Closer ?
{152423}{152481}I could try.
{152641}{152738}General,|I've lost them.
{152740}{152872}The magnetism of the mine field|is disrupting our instruments.
{152874}{152970}Wait !|I see something.
{152972}{153071}Yes. Yes !|There they are.
{153073}{153153}- Get back on their tail.|- I can't, sir.
{153155}{153270}- What ? Why not ?|- Because they're coming right at us.
{153272}{153341}Fire at will.
{153471}{153599}Whoo ! We're getting hammered,|Jason ! Return fire ?
{153601}{153685}No ! Divert all energy|to the armor !
{153687}{153756}How adorable--
{153758}{153845}the actors are going|to play war with me.
{153847}{153991}- Sarris' ship, accelerating|toward us at mark 2.|- Accelerate to mark 4.
{154119}{154228}Let me remind you, sonny:
{154230}{154304}I am a general.
{154307}{154396}If you are counting on me|to blink,
{154399}{154511}then you are making|a deadly mistake.
{154513}{154618}Well, let me tell you|something, Sarris.
{154621}{154767}It doesn't take a great actor to|recognize a bad one. You're sweating.
{154769}{154840}Armor almost gone, Jason !
{154842}{154996}You fool ! You failed to realize|that with your armor gone,
{154998}{155135}my ship will tear through yours|like tissue paper.
{155138}{155289}And what you fail to realize is|my ship is dragging mines.
{155361}{155444}Oh, no !|Turn, turn !
{155928}{155986}- We did it !|- [ Cheering ]
{156034}{156096}Yes ! Yes !
{156099}{156157}- Yes ! [ Laughing ]|- [ Cheering Continues ]
{156194}{156265}Yes ! Yes !
{156297}{156469}- [ Mumbling ]|- Mathesar !
{156521}{156614}- Oh, my God, you're alive.|- [ Groaning ]
{156617}{156762}- Come here.|- The ship was a model as big as this.
{156764}{156841}A very clever|deception indeed.
{156844}{156945}[ Laughing, Cheering ]
{156947}{157005}[ Cheering ]
{157127}{157186}Set a course|for home, Commander ?
{157188}{157278}- Can you do that ?|- Oh, yeah, just point and click.
{157281}{157370}- But we're gonna have to go|through the black hole.|- Any objections ?
{157373}{157429}[ All Scoffing ]
{157431}{157519}All right, set her up.
{157618}{157676}What's the matter,|Mathesar ?
{157730}{157823}We were hoping|you could come with us.
{157826}{157944}M-My people|have no commander.
{157946}{158035}[ Sighing ]|Mathesar, I think your people...
{158038}{158123}have a great commander.
{158277}{158335}[ Whimpering ]
{158406}{158495}All right, Tommy,|take us into the black hole.
{158972}{159045}- We're out !|- We're going home.
{159047}{159170}- Systems register functional.|- All systems are working, Commander.
{159173}{159305}Jason, before the black hole, there was|an energy surge from Sarris' ship.
{159307}{159431}Let's not worry about that|right now, Alexander.|Fred, what are you doing up here ?
{159433}{159576}Shouldn't you be downstairs|until we dec-- Hey, you can put|an eye out with that thing.
{159653}{159719}Fred ?
{159721}{159777}[ Groaning ]
{160188}{160255}[ Yelling In Slow Motion ]|No !
{160982}{161110}Mathesar ! Activate|the Omega 13 !
{161833}{161923}- We're out !|- We're going home !
{161957}{162026}Systems register functional.
{162028}{162086}All systems are working,|Commander.
{162088}{162221}Jason, before the black hole, there was|an energy surge from Sarris' ship.
{162265}{162400}[ Gwen ] Jason, what are you doing ?|What are you doing ?
{162445}{162520}Let go of me. Let--|It's not Fred.
{162523}{162641}That's Sarris. Listen to me.|I'm telling you, that's not Fred,|that's Sarris.
{162644}{162716}He's gonna try to kill|all of us.
{162718}{162778}[ Growling ]
{162961}{163042}Never give up,|never surrender.
{163093}{163191}Jason. Jason !|I can't slow it down !
{163193}{163272}Our ship is too big|to enter the atmosphere.
{163274}{163354}We need to separate,|or we'll die.
{163494}{163570}We gotta do it.|It's our only hope, Mathesar.
{163573}{163631}Thank you.
{163633}{163706}Crew to|the secondary deck.
{163756}{163845}Mathesar !
{163909}{163982}Good-bye, my friends.
{164142}{164257}Fred, get up to command deck.|We're separating.
{165023}{165096}On, Teb, on !
{165321}{165394}This is the third day|of the Galaxy Con,
{165396}{165524}and Jason Nesmith and his entire crew|are no-shows here at the big event,
{165526}{165616}much to the disappointment|of all these fans, knows as Questoids.
{165619}{165724}- Bye. Be back soon.|- Wait a minute. Where you going|with those fireworks ?
{165727}{165846}Well, the Protector|got super accelerated|coming out of the black hole,
{165849}{165919}and it nailed the atmosphere|at mark 15,
{165921}{166006}which, you guys know,|is pretty unstable obviously,
{166008}{166107}so we're gonna help Laredo guide it|on the vox ultra-frequency carrier...
{166109}{166181}and use Roman candles|for visual confirmation.
{166183}{166265}A-All right,|dinner's at 7:00.
{166360}{166463}- Well, he's outside.|- Hmm.
{167473}{167575}[ Chattering ]
{167631}{167702}[ Screaming ]
{168044}{168117}[ Murmuring ]
{168703}{168784}[ Coughing ]
{168837}{168895}[ Coughing Continues ]
{168946}{169024}[ Crowd Cheering ]
{169090}{169186}Lieutenant Laredo--|Tommy Webber !
{169239}{169316}Hi, Tommy !
{169379}{169484}The beautiful Tawny Madison--|Gwen DeMarco !
{169487}{169605}Yes ! Yes !
{169640}{169705}Wow, what effects !
{169707}{169855}Another shipmate !|Yes, the more, the merrier !
{169899}{170046}The ship's Tech Sergeant Chen,|Fred Kwan, and a friend.
{170048}{170183}Dr. Lazarus--|Alexander Dane !
{170186}{170275}Give a big hand.|He's British !
{170278}{170351}Yes, sir !
{170353}{170477}Commander Peter Quincy Taggart--|Jason Nesmith !
{170708}{170790}Great driving, Tommy.
{170792}{170850}Yeah ! Yes !
{171102}{171165}Quick, quick, quick.|[ Yelling ]
{171392}{171506}- [ Cheering ]|- [ Emcee Shouting ]
{171508}{171589}Mr. Jason Nesmith !
{171636}{171792}Come on, give it up for the crew,|the N.S.E.A. Protector !
{171794}{171925}Ah, true love !|Yes !
{171959}{172020}Wow !
{172023}{172085}[ Screaming ]
{172178}{172246}They're here for you folks.|Give it up !
{172248}{172306}What a show !
{172374}{172449}What a show ! Yes !
{172521}{172596}Yes ! Yes !
{172671}{172744}Come on, give it up !|Give it all up...
{172746}{172838}for the crew of your favorite show,|Galaxy Quest !
{172841}{172899}Wow !
{172977}{173050}Come on, come on !
{173336}{173448}Don't forget to buy Galaxy Quest|T-shirts on your way out.
{173450}{173508}Thank you.
{173510}{173568}Whoo !
{173652}{173726}And now,|back again after 18 years,
{173728}{173816}the New Adventures of Galaxy Quest.
{183274}{183384}[ Mathesar ]|Never give up, never surrender.
